### ISSUE TITLE
Expand upon webapp quickstart and write "The Tutorial" in the docs repo

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/docs#100]
Tutorial flow 
- Author an app 
    - Intro to app model - create an application, gateway, HTTP route, and a service
- Run an app 
    - rad env init dev 
     - rad app run (local experience...)
     - Monitor app (Public Preview)
- Add portability 
     - swap a resource for a connector resource     
     - rad env init azure
     - view app in Azure Portal (Public Preview)  

What we want them to takeaway 
- they feel ready to map their own app to Radius 
- I know how to use local dev for quick app dev/test work 
Notes
- every Radius user will benefit from it 
- only 1 tutorial, aim for 30 min
- evolve from Webapp+DB 
- note: doesn't contain Dapr connector. May add Dapr section later. 

Note: we also want to have a Portability quickstart. Let's have 101 level info on portability in The Tutorial and 201 level info in the Portability Quickstart. 

We want to move away from teaching Bicep
- remove places where we talk about teaching "The basic syntax of the Bicep language"

**Comment by Reshrahim** [comment]
New Flow 

Flow to indicate the handoffs between two personas right from the beginning
- Setup a Radius environment
   - prereqs of creating a cluster (prescriptive on what cluster works with Radius)
   - install radius on the control plane 
- Define an application via the Radius application model
- Add connector resources for portability
- Deploy the application onto a environment
- View the application post-deployment
- Swap the connector resource for an Azure resource and deploy to an environmnet with Azure cloud provider configured
