### ISSUE TITLE
Clean up containers apps store sample

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/docs#101]

**Comment by jasonviviano** [comment]
Based on feedback by @AaronCrawfis yesterday, need to finish up the task by:

- Keeping documents that refer to the architecture in the official website, move the code to the sample repo and remove other pages in regards to the container app.
- Spin into a quickstart for local to cloud portability.

**Comment by Reshrahim** [comment]
Container apps sample needs to be moved under reference docs section in our new docs

**Comment by jasonviviano** [comment]
Decided against the local to cloud portability quickstart just don't think there's enough there to validate a quickstart after looking through it and comparing it with what's shown on the new environment page. Believe the portability commands/ settings fit more there than a separate quickstart. 

Moved the container apps sample to reference docs section: https://github.com/project-radius/docs/pull/183
