### ISSUE TITLE
Create a new quickstart on local dev

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/docs#102]
Quickstarts:
- Dapr+Radius
- Consuming Starters
- Writing templates 
- advanced features in local dev (e.g. hot reload)
- Radius in CI/CD 

Notes
- Quickstarts != product pages for that topic
- assumes you're already familiar with Rad CLI & app model 
- For Public Preview, we will need some examples/quickstarts for various contributing workflows (e.g. Starters)
- have tons of links to product pages 

[AB#6626](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/6626)

**Comment by jasonviviano** [comment]
Synced with @AaronCrawfis yesterday, based on the feedback have to implement some new changes to:

- Point users to sample repo for any application references, so remove application setup stage
- Avoid using `rad app init` as sample application doesn't use infra
- Basic information in regards to the local kubernetes cluster created
- Basic information in regards to the container registry
- Explain why users need to run certain actions on a superficial level but point to in depth docs for more exploration.

**Comment by AaronCrawfis** [comment]
Closing as we now have a new first app experience
