### ISSUE TITLE
refresh our Getting Started experience into a single-page, quick flow

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#109]
https://github.com/project-radius/docs/blob/edge/docs/content/getting-started/_index.md

some inspiration from Jason: 
https://www.rust-lang.org/learn/get-started

**Comment by jasonviviano** [comment]
Synced with @AaronCrawfis for feedback yesterday, only thing missing to complete this now should be:

- Adding a codespace reference
- Seeing if its possible to add the feedback mechanism that Docsy enables. Have to double check google analytics sheet that was setup a while back

**Comment by emily-potyraj** [comment]
- 2 options: either install on local machine with normal "install CLI... " flow or use codespaces
- add "hello world" app with only resources: app, container that prints "hello world" or something
- add a few sentences about what an env is vs. an app 
- we do want to enable the Docsy feedback mechanism

**Comment by jasonviviano** [comment]
Added a PR with just the codespace section and a table as last week it was agreed that a tutorial section right now at the getting started page would be too detail heavy.

PR: https://github.com/project-radius/docs/pull/186
