### ISSUE TITLE
Dependancy Bug: Moby's external DNS requests from 'internal' networks could lead to data exfiltration

### ISSUE THREAD

**Issue by jasonviviano** [radius-project/docs#1091]
## Describe the bug

Dependabot alert: https://github.com/radius-project/docs/security/dependabot/163

## Steps to reproduce

Check out the vulnerability section of the repo: https://github.com/radius-project/docs/security/dependabot

## Expected behavior

No vulnerability

## Screenshots
N/A

## Additional context
N/A

[AB#11618](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11618)

**Comment by willtsai** [comment]
closing as fixed since dependabot looks to have patched it already: https://github.com/radius-project/docs/security/dependabot/163
