### ISSUE TITLE
Dependancy Bug: Classic builder cache poisoning

### ISSUE THREAD

**Issue by jasonviviano** [radius-project/docs#1092]
## Describe the bug

Dependabot alert: https://github.com/radius-project/docs/security/dependabot/162

## Steps to reproduce

Check out the vulnerability section of the repo: https://github.com/radius-project/docs/security/dependabot

## Expected behavior

No vulnerability

## Screenshots
N/A

## Additional context
N/A

[AB#11619](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11619)

**Comment by Reshrahim** [comment]
closing this as the dependabort alert is fixed
