### ISSUE TITLE
Dependency Bug: PostCSS line return parsing error

### ISSUE THREAD

**Issue by jasonviviano** [radius-project/docs#1094]
## Describe the bug

Dependabot alert: https://github.com/radius-project/docs/security/dependabot/128

## Steps to reproduce

Check out the vulnerability section of the repo: https://github.com/radius-project/docs/security/dependabot

## Expected behavior

No vulnerability

## Screenshots
N/A

## Additional context
N/A

[AB#11621](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11621)

**Comment by sylvainsf** [comment]
Close not fix, we don't accept non PR changes to Docs
