### ISSUE TITLE
rad-ci-bot doesn't have enough permission to update default branch via release workflow

### ISSUE THREAD

**Issue by youngbupark** [radius-project/docs#1096]
## Problem

[release workflow](https://github.com/radius-project/docs/actions/workflows/release.yaml) uses `rad-ci-bot` to release docs. Once the release is done, we always need to change the default branch to the latest version branch. Changing default branch requires admin permission. `rad-ci-bot` doesn't have this permission, so changing default branch step in release workflow is failing. 

## Solution

Assign admin permission to `rad-ci-bot`. 
> NOTE: samples repo should have the same change. 

[AB#11666](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11666)

**Comment by youngbupark** [comment]
@willtsai @willdavsmith @sylvainsf @nicolejms If there is no security concern, it makes sense to assign admin permission to rad-ci-bot for the automation.

**Comment by sylvainsf** [comment]
We need to create a granular permission role for `rad-ci-bot` to enable it to update the tag.

**Comment by willtsai** [comment]
done, updated the role from Write to Admin for `rad-ci-bot` in both `docs` and `samples` repos.
