### ISSUE TITLE
Verify that the CLI can get the gateway IP address, and add to docs & tutorials

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/docs#11]

**Comment by willdavsmith** [comment]
Does this change involve creating a new CLI command as with https://github.com/project-radius/radius/issues/2306 or did you have something else in mind? @amanbha @AaronCrawfis

**Comment by willdavsmith** [comment]
AFAIK currently there's no way to get the gateway address via rad CLI.

**Comment by AaronCrawfis** [comment]
> Does this change involve creating a new CLI command as with [project-radius/radius#2306](https://github.com/project-radius/radius/issues/2306) or did you have something else in mind? @amanbha @AaronCrawfis

Yep this would be the outcome we want. Closing this issue to track the other one
