### ISSUE TITLE
Move Dapr trait reference doc out of connectors

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/docs#110]
Not a connector

https://edge.radapp.dev/reference/resource-schema/connector-schema/dapr-schema/trait/

[AB#7089](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7089)

**Comment by emily-potyraj** [comment]
let's add it as a sub-type here for now:
https://edge.radapp.dev/reference/resource-schema/core-schema/container-schema/

let's also rename to "properties" instead of "sub-types" to avoid confusion.
thanks @kachawla for the recommendations here!

**Comment by emily-potyraj** [comment]
was rearranging some things around here anyways, so just made the change. hope that's ok!

**Comment by emily-potyraj** [comment]
need to refresh the tree reorg PR, including this change.

**Comment by emily-potyraj** [comment]
fyi as of v0.12, this is "Dapr Sidecar Extension"
(https://github.com/project-radius/docs/pull/185/files#diff-808d771936d9ad64f07265bb8e04a83726a286d67702eeffc6652b2476931a34)

**Comment by AaronCrawfis** [comment]
Closing as we're switch to `Applications.Dapr`
