### ISSUE TITLE
Add PodSpec example to use the existing k8s secret in Radius container resource

### ISSUE THREAD

**Issue by youngbupark** [radius-project/docs#1101]
## What content needs to be created or modified?

Add additional PodSpec Patch example to reference k8s secret in Radius container resource.
 
## Describe the solution you'd like

As a Radius user, I can reference my existing kubernetes secret in Radius container resource using PodSpec Patch.

## Where should the new material be placed?

This document should be placed in https://github.com/radius-project/docs/blob/v0.32/docs/content/guides/author-apps/kubernetes/how-to-patch-pod/index.md

## The associated pull request from the Radius code repo, if applicable

N/A

## Additional context

[AB#11704](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11704)

**Comment by youngbupark** [comment]
@jasonviviano @willtsai Nick wants to contribute to the documentation for the PodSpec example to use the existing k8s secret. Where is the best place to add this example?

**Comment by jasonviviano** [comment]
> @jasonviviano @willtsai Nick wants to contribute to the documentation for the PodSpec example to use the existing k8s secret. Where is the best place to add this example?

I'd wait for @willtsai ultimately on the answer here but a good place to start as a position would be Kubernetes section under authoring: https://docs.radapp.io/guides/author-apps/kubernetes/overview/ but looking at the PR that's what's already being used!

**Comment by nicolejms** [comment]
this was done

**Comment by willtsai** [comment]
fixed by: https://github.com/radius-project/docs/pull/1100
