### ISSUE TITLE
Fix upmerge docs to edge workflow

### ISSUE THREAD

**Issue by sk593** [radius-project/docs#1163]
## What content needs to be created or modified?
The upmerge docs workflow needs to be fixed. It fails to commit changes from the previous branch

https://github.com/radius-project/docs/actions/workflows/upmerge.yaml

## Additional context

[AB#12891](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/12891)

**Comment by sylvainsf** [comment]
@sk593 Could you provide an example regression?

**Comment by sk593** [comment]
> @sk593 Could you provide an example regression?

Looks like the logs expired but the failure was similar to this: 

```
Run export SOURCE_BRANCH=$(basename refs/heads/v0.35)
Upmerging docs from v0.35 to edge
From https://github.com/radius-project/docs
 * branch            v0.35      -> FETCH_HEAD
<change info for updated code>
On branch upmerge/2024-07-18-1fd3
nothing to commit, working tree clean
Error: Process completed with exit code 1.
```
