### ISSUE TITLE
Should kubectl be a prerequisite for creating a Radius environment?

### ISSUE THREAD

**Issue by ihood** [radius-project/docs#120]
**Overview of feature request**
kubectl is needed to deploy an Azure Radius environment as described in the docs. From following the ['Getting started'](https://radapp.dev/getting-started/) guide, I was never instructed that kubectl was a pre-requisite. When I attempted to create an Azure Radius environment and deploy it, I was thrown an error as shown below and deployment failed. Should kubectl be listed as a prerequisite in the docs alongside Az CLI [here?](https://radapp.dev/getting-started/install-cli/#pre-requisites)

`failed to run command: exec: "kubectl": executable file not found in $PATH`

**Comment by emily-potyraj** [comment]
@Reshrahim @AaronCrawfis - are we planning to do anything here for v0.12?

**Comment by emily-potyraj** [comment]
shall we close this one for now as not-planned? we can reopen if needed.
