### ISSUE TITLE
Reference link return 404 not found

### ISSUE THREAD

**Issue by lbzss** [radius-project/docs#1204]
## Describe the bug
https://docs.radapp.io/reference/cli/rad_install_kubernetes/
The document mentioned links below return 404 not found.
**https://docs.radapp.io/concepts/architecture/**
**https://docs.radapp.io/operations/platforms/kubernetes/install/**

## Screenshots
![image](https://github.com/user-attachments/assets/f1e2a136-577a-4b77-9d25-11cd79384b2f)

[AB#13086](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/13086)

**Comment by Reshrahim** [comment]
Thanks for reporting this. Submitted a PR to update the links -https://github.com/radius-project/radius/pull/7849
