### ISSUE TITLE
Need to add commit sign-off to the PR created by the upmerge workflow

### ISSUE THREAD

**Issue by ytimocin** [radius-project/docs#1233]
Need to add commit sign-off to the PR created by the upmerge workflow

[AB#13198](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/13198)

**Comment by lakshmimsft** [comment]
@ytimocin pls add more context. Clarify impact to the release process.

**Comment by ytimocin** [comment]
The PR that is created by this [workflow](https://github.com/radius-project/docs/blob/v0.37/.github/workflows/upmerge.yaml#L82) has a commit that is not signed off. I think (but I am not sure) the bot that creates this PR needs a DCO permission. See an example [here](https://github.com/radius-project/docs/pull/1236/checks?check_run_id=30215885472).

**Comment by ytimocin** [comment]
There is no impact to the release process. You just need to manually set the DCO to pass.
