### ISSUE TITLE
Document postgres support in Radius

### ISSUE THREAD

**Issue by nithyatsu** [radius-project/docs#1252]
Once we introduce configs that support postgres as datastore for Radius (https://github.com/radius-project/radius/issues/7975)  we should document the configs. 

[AB#13383](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/13383)

**Comment by lakshmimsft** [comment]
This will be included as part of radius-project/radius#7975
