### ISSUE TITLE
Add signoff to `Upmerge docs to edge` workflow

### ISSUE THREAD

**Issue by willdavsmith** [radius-project/docs#1270]
The [`Upmerge docs to edge`](https://github.com/radius-project/docs/actions/workflows/upmerge.yaml) workflow does not include a signoff message in the commit: https://github.com/radius-project/docs/blob/7ed3cea5de7f14f7c174cab0b60a54b6af114a38/.github/workflows/upmerge.yaml#L66

This causes DCO to fail during the release process. We should add a signoff flag to the `git merge` command.
 

[AB#13660](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/13660)

**Comment by ytimocin** [comment]
Closing this now @willdavsmith. You can re-open if it is not fixed already.

**Comment by kachawla** [comment]
This hasn't been fixed yet, re-opening and removing triage label.

**Comment by ytimocin** [comment]
Needs to be worked on. The commit that added the sign-off was removed.
