### ISSUE TITLE
Add explicit Kubernetes support to the Container Apps Sample

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/docs#128]
Today there isn't expicit support for Kubernetes in the Container Apps sample.

We should either add docs on how to deploy to Kubernetes, using container resources, or wait for 0.12 for Azure resources to be deployed from a Kubernetes resource

**Comment by jasonviviano** [comment]
Closing as the application will be moved to the sample repo with a basic readme explaining the architecture and will setup profiles in the `rad.yaml` to differentiate between Azure/Kubernetes and local. Will use issue: #101 to track.
