### ISSUE TITLE
Refresh connections docs

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/docs#130]
main page with all the juicy details about how connections work and what they do under the hood:
https://edge.radapp.dev/author-apps/resource-library/connectors/

we should also make sure we have a summary note about how connections are useful in our "app model overview" page:
https://edge.radapp.dev/concepts/defining-an-app/app-model-overview/

Let's try to pull heavily from our Product deck's speaker notes about Connections.

**Comment by emily-potyraj** [comment]
@ihood @AaronCrawfis - do we feel like we want to do anything else here for v0.12 or do we like the current state of the edge branch?
