### ISSUE TITLE
Azure account 'owner' requirement clarification / suggestions.

### ISSUE THREAD

**Issue by jongio** [radius-project/docs#14]
Here we tell the user the account must have Owner. 
https://radapp.dev/getting-started/create-environment/

For me, that is like saying 'make the user admin on the box', which a lot of folks won't be comfortable with.

1. Is contrib not enough? 
2. Would be good to explain why owner is required.
3. Would be good to explain what explicit permissions are required, so the user could create their own role.  Or better yet, have a bicep file that has all the roles and allowed them to create the role in their sub and assign and account to it.

**Comment by rynowak** [comment]
> For me, that is like saying 'make the user admin on the box', which a lot of folks won't be comfortable with.
> 

We should improve the docs and while we do that also make it clear that this is a point-in-time limitation until an actual service exists 👍

**Comment by AaronCrawfis** [comment]
Clarification was added, with note this requirement will be resolved once Azure service is built
