### ISSUE TITLE
Create a codespace setup for doc testing

### ISSUE THREAD

**Issue by jasonviviano** [radius-project/docs#142]
## Description
Create a .devcontainer for codespace that sets up Hugo and allows users to just run `hugo server` and start interacting with the documents

[AB#5509](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5509)

**Comment by AaronCrawfis** [comment]
Completed as part of https://github.com/project-radius/docs/pull/454
