### ISSUE TITLE
Create a Connectors main page 

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#147]
We have a blank page we should fill in about why connectors are awesome and how they enable portability:
https://edge.radapp.dev/concepts/defining-an-app/connectors-model/

fyi detailed schemas for our connector types are in the "Reference > Resource schemas" section: 
https://edge.radapp.dev/reference/resource-schema/connector-schema/

Let's try to pull heavily from our Product deck's speaker notes about Connectors.

**Comment by ihood** [comment]
- [x] connectors concept introduction
- [x] example of using connectors
- [ ] diagrams
- [ ] code snippet using connectors
- [ ] reference to connector types
