### ISSUE TITLE
scrub docs to switch "traits" to "extensions"

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#155]
it got renamed with v0.12 code 

@jasonviviano do you have the bandwidth to take a look at this one? 
I think @shalabhms can be our technical expert here if we have questions. 

for updating bicep files, we need to move them to corerp anyways, not sure if we want to do the overall switch to corerp at the same time as changing "trait" to "extension" in them.

**Comment by jasonviviano** [comment]
@shalabhms  Hey! Whenever you have time could you take a look at the reworded sections just want to make sure I didn't replace trait somewhere were maybe it should've remained for Dapr.

@emily-potyraj  Also I found this section in the docs in the Dapr Quickstart/Add Dapr section that's linking to some `//Traits` for snippets but i couldn't understand if it was linking to the original `traits.bicep` file or if maybe I'm not seeing the tags represented in the `connection.bicep` file this is referring to:

`{{< rad file="snippets/connection.bicep" embed=true replace-key-container="//CONTAINER" replace-value-container="container: {...}" replace-key-traits="//TRAITS" replace-value-traits="traits: [...]" replace-key-route="//ROUTE" replace-value-route="resource daprBackend 'dapr.io.InvokeHttpRoute' = {...}" replace-key-connector="//CONNECTOR" replace-value-connector="resource ordersStateStore 'dapr.io.StateStore' existing = {...}" replace-key-starter="//STARTER" replace-value-starter="module stateStoreStarter 'br:radius.azurecr.io/starters/dapr-statestore:latest' = {...}" >}}`

**Comment by AaronCrawfis** [comment]
> Also I found this section in the docs in the Dapr Quickstart/Add Dapr section that's linking to some //Traits for snippets but i couldn't understand if it was linking to the original traits.bicep file or if maybe I'm not seeing the tags represented in the connection.bicep file this is referring to:

https://edge.radapp.dev/contributing/contributing-docs/#code-snippets

**Comment by jasonviviano** [comment]
Yeah i understand its a code snippet however it doesn't actually seem to exist in the file it says it does which would be the `connection.bicep` @AaronCrawfis
