### ISSUE TITLE
add documentation about app name limitations

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#159]
documentation side of https://github.com/project-radius/radius/issues/2078

dev changes to handle longer names will be in v0.13+

**Comment by emily-potyraj** [comment]
@lakshmimsft - since you've got the details of https://github.com/project-radius/radius/issues/2078, 
could you please help make a note for our docs about the current limitation? 

Let's put it on this page for now https://edge.radapp.dev/reference/known-issues/

**Comment by jkotalik** [comment]
To be specific, the limit of 64 characters is put on the combination of the application name + "-" + resource name right now.

I hit this frequently, I'd love to be able to fix it ASAP.

**Comment by emily-potyraj** [comment]
thanks @jkotalik. I brought the dev-side change ticket back into "proposed for v0.12" per the triage process of "if we bump something out to v0.12 and somebody wants to go to bat for it coming back into v0.12, great" 🙂

**Comment by emily-potyraj** [comment]
also describe results of these other issues
- https://github.com/project-radius/radius/issues/2925
  - and what's our casing storying for each resource type in general? 
- https://github.com/project-radius/radius/issues/2994

**Comment by emily-potyraj** [comment]
**capitalization** 
- If you create a Radius resource with a name that contains capital letters (e.g. containerA), then that resource name of the corresponding Kubernetes resources will be lowercased as required by Kubernetes.
  - So rad CLI commands will show the resource name as originally declared by the user. 
  - All Radius CLI commands are case-insensitive. We preserve the case that users prefer, but we case-insensitive where we do comparisons (e.g. name uniqueness). 
  - kubectl commands will show the name lowercased.
 
**allowed characters**
The current limitations of resource names are:
- contain at most 63 user-entered characters
- contain only alphanumeric characters or '-' 
- start with an alphabetic character
- end with an alphanumeric character

> a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')

LJ: updated the above for 'end with alphanumeric character' instead of alphabetic

**Comment by lakshmimsft** [comment]
@emily-potyraj one note on the above summarized statements:
the user can enter in commands to rad-cli (where names are case-insensitive) but the output seen in subsequent commands is lower cased.

eg.

```
after  deploying an application with application name: smallAppNAME14UPD
and container name: smallnameCONTAINER20UPD

and running the following commands:
rad application list
RESOURCE           TYPE
smallappname14upd  applications.core/applications

rad resource list -a smallAppName14upd
RESOURCE                 TYPE
smallnamecontainer20upd  applications.core/containers
```

**Comment by emily-potyraj** [comment]
> @emily-potyraj one note on the above summarized statements: the user can enter in commands to rad-cli (where names are case-insensitive) but the output seen in subsequent commands is lower cased.

@lakshmimsft - awesome catch. I would think that's a bug. Can you please file a separate ticket for us to chase that issue? Thanks
