### ISSUE TITLE
Update validation logic to check all Bicep files, not just `corerp-*.bicep`

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/docs#161]

**Comment by willdavsmith** [comment]
today, files not prefixed will be checked according to the CustomRP-based bicep compiler: https://github.com/project-radius/docs/blob/edge/.github/scripts/validate-bicep-customrp.sh

**Comment by AaronCrawfis** [comment]
Closing as we no longer validate customrp in docs
