### ISSUE TITLE
Document environment parameter injection behavior

### ISSUE THREAD

**Issue by jkotalik** [radius-project/docs#169]
See https://github.com/project-radius/radius/pull/2817

parameter environment is auto injected into your app via radius, unless specified on the command line as a parameter argument.

**Comment by emily-potyraj** [comment]
@jasonviviano @Reshrahim @ihood - any of y'all have a suggestion for where this one should land in the docs and want to take it on?

**Comment by emily-potyraj** [comment]
group decision: this content should fall somewhere under the resource schema page

**Comment by jasonviviano** [comment]
Closed with: https://github.com/project-radius/docs/pull/289
