### ISSUE TITLE
Reconfigure Microsoft Clarity metrics for docs feedback

### ISSUE THREAD

**Issue by jasonviviano** [radius-project/docs#187]
## Description
There seems to have been a Google Analytics account and a current Microsoft Clarity account to keep track of certain metrics for our docs but there needs to be a review of all the metrics we collect and making sure that user feedback can be collected correctly.

Clarity: Link only works if you're a PM but its [here](https://clarity.microsoft.com/projects/view/bffu3v0r2p/dashboard?date=Last%203%20days)

**Comment by emily-potyraj** [comment]
@jasonviviano @AaronCrawfis - are we still planning to make this change for v0.12?

**Comment by AaronCrawfis** [comment]
> @jasonviviano @AaronCrawfis - are we still planning to make this change for v0.12?

I don't believe there's anything to do yet. Met with Jason awhile back, Clarity should be collecting all the metrics we need at the moment. However if there's a specific scenario for what we want to track/dig into that Clarity doesn't tell us we can revisit this.

**Comment by AaronCrawfis** [comment]
Closing. Please reopen if you have any items you wish to address
