### ISSUE TITLE
add documentation about `location` best practices

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#189]
- documentation (and need to get broader agreement on best practices here) 
  - when to use `resourceGroup().location`
  - when do users need multiple location params? 
- need to scrub docs for any bicep files that need this change 
- any changes in main Radius tests needed?

**Comment by emily-potyraj** [comment]
as part of this PR, let's also paste into this issue example output of how `resourceGroup().location` currently evaluates for both azure resources and radius resources.

**Comment by emily-potyraj** [comment]
triage note: having a huddle on this today to determine best practices. committed to v0.12.

**Comment by emily-potyraj** [comment]
**Facts**

- The `resourceGroup()` function will always be scoped to Azure resource groups specifically. 
  - Defining the `resourceGroup()` function any other way (e.g. to refer to a UCP resource group) will break because there needs to be a function to refer to which Azure resource group being deployed to. 
  - So, `resourceGroup().location` is not usable for non-Azure resources because we can't redefine what that function is for. 
-  Any Azure resource, regardless of scenario now and in the future,`resourceGroup().location` is correct for Azure resources.
  - `global` location is NOT correct for Azure because there's more than 1 location.
-   _All_ resource PUT operations regardless of scenario must contain a location property for all resources.  (This is an ARM decision, not a Radius decision.)


**Implications for Radius**
- Decision: `resourceGroup().location` will return information from the Azure resource group configured as part of the Azure cloud provider. 
  - If no Azure cloud provider has been configured, the deployment will fail. 
  - --> We should make this so for v0.12. 

**For v0.12**
- In v0.12, we do NOT YET support deploying the exact same bicep file with the same `location` value to both Azure and Radius planes. 
  - For v0.12, for Radius resources, we will tell users to hardcode `location: 'global'` as a stopgap measure (because we cannot use `resourceGroup().location` and global is the correct term when there's only 1 location.)
  - In the far future, we will support scenarios where location is meaningful in standalone. 
    - **Decision for v0.12: we DO want to start validating that the location is filled as 'global'** 
      - We will have to validate this value eventually. 
    -  **Decision for v0.12: We need to figure out what the behavior is of the `resourceGroup()` function when the deployment doesn't have an Azure scope**
       - We should try to give the user a friendly error that "It looks like you're tryna do Azure stuff but don't have an Azure cloud provider configured"

**Post v0.12**
- We want to move location out of the bicep file. 
  - We _may_ move it to provider config (type in command line or it's in config.yaml). 
- We should consider whether UCP resource groups still called "resource groups." (Needs more extensive design.)

**Comment by emily-potyraj** [comment]
anything else to do here, or shall we close as done?

**Comment by AaronCrawfis** [comment]
> anything else to do here, or shall we close as done?

I need to do one last find/replace to standardize the use of 'global' and will close afterwards.
