### ISSUE TITLE
Tutorials should link to both repo and .zip files

### ISSUE THREAD

**Issue by jongio** [radius-project/docs#19]
Here: https://radapp.dev/getting-started/tutorial/webapp/webapp-overview/

Links to: https://radapp.dev/tutorial/webapp.zip

I'd like it to link to a GH repo so I can easily view the src.
azsdke2e
azsdke2e3

[AB#1073](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/1073)

**Comment by emily-potyraj** [comment]
@AaronCrawfis - you're the guru here. 

I believe you setup the zip files for our tutorial apps so that we could make sure the user got the right version of it from our repo (based on which release's version of the docs page they're on). 

What do you think about adding a direct link as well?

**Comment by jongio** [comment]
Yeah, they may want to PR it or easily clone.

**Comment by AaronCrawfis** [comment]
Eventually we'll link to GitHub to clone. The main reason we're not right now is because the private preview participants do not have access to this repo so they'll get a 404. ZIP files prevent us from tons of pings saying "can I have access".

**Comment by AaronCrawfis** [comment]
Waiting on project-radius/radius#267
