### ISSUE TITLE
Describe the timeout and retry policy

### ISSUE THREAD

**Issue by youngbupark** [radius-project/docs#194]
Each service in radius has its own timeout/retry policy/throttle limit. Each component should have the clear error message and user hit such limit. Typically, those numbers are constantly tuned based on the data (customer feedback and telemetry).

Here is the examples of the limit we may want to document:
* Deployment engine - write / delete timeout and retry
* RP - Timeouts / retry policy for async operation per resource type

**Comment by emily-potyraj** [comment]
@youngbupark - who on the dev team can help capture the current timeout and retry info?

**Comment by youngbupark** [comment]
> @youngbupark - who on the dev team can help capture the current timeout and retry info?

@emily-potyraj - UCP/RP/DE have their own timeout and retry count. 

* RP - I can provide the timeout and retry count per resource-type when I am back to the office next week.
* UCP - @vinayada1 - upstream service timeout
* DE - @jkotalik

**Comment by emily-potyraj** [comment]
triage note: committed to add this doc in v0.12
@jasonviviano - could you please help shepherd collecting the bits of info we need here? @rynowak says we can sync with him if needed. thanks

**Comment by youngbupark** [comment]
## Resource provider

### Timeouts

Here is the default timeout per API type. Asynchronous timeout varies per resource type.

* Default synchronous API timeout : 60 seconds. It depends on UCP gateway timeout.
* Default asynchronous API timeout : 120 seconds

### Asynchronous operation retry policy

Each resource type controller decide whether it will retry to process the operation when it fails, but the current async operation controller immediately marks any errors as `Failed` operation except for the following scenario:
- Panic happens while processing the async operation by code defect (retry once, then mark the operation `Failed`)
- RP process exits by unexpected process crashes (such as node failure, memory leak) and redeploying Radius.  (retry once , then mark the operation `Failed`)

> Note: Retry count will be different based on environment. It is hard to say what the best numbers are. As the other service team does, we will learn and tune the number based on customer feedback and telemetry.

1. Applications.Core Resource Provider

| Resource Type | Operation | API Type | Server Timeout (Seconds) | Async operation retry condition  |
|----------------|----------|-----------|----------|-----|
| Applications.Core/environments | LIST/GET/PUT/PATCH/DELETE | Synchronous | default |   |
| Applications.Core/applications | LIST/GET/PUT/PATCH/DELETE | Synchronous | default |   |
| Applications.Core/containers | LIST/GET | Synchronous | default | |
| Applications.Core/containers | PUT/PATCH/DELETE | Asynchronous | 300 | default |
| Applications.Core/gateways | LIST/GET | Synchronous | default  | |
| Applications.Core/gateways | PUT/PATCH/DELETE | Asynchronous | default | default |
| Applications.Core/httpRoutes | LIST/GET | Synchronous | default  | |
| Applications.Core/httpRoutes | PUT/PATCH/DELETE | Asynchronous | default | default |

2. Applications.Connector RP

| Resource Type | Operation | API Type | Server Timeout (Seconds) | Async operation retry condition |
|----------------|----------|-----------|----------|-----|
| Applications.Connector/daprInvokeHttpRoutes | LIST/GET/PUT/PATCH/DELETE | Synchronous | default | |
| Applications.Connector/daprInvokeHttpRoutes | POST ListSecret | Synchronous | default | |
| Applications.Connector/daprPubSubBrokers | LIST/GET/PUT/PATCH/DELETE | Synchronous | default  ||
| Applications.Connector/daprPubSubBrokers | POST ListSecret | Synchronous | default  ||
| Applications.Connector/daprSecretStores | LIST/GET/PUT/PATCH/DELETE | Synchronous | default  ||
| Applications.Connector/daprSecretStores | POST ListSecret | Synchronous | default ||
| Applications.Connector/daprStateStores | LIST/GET/PUT/PATCH/DELETE | Synchronous | default  ||
| Applications.Connector/daprStateStores | POST ListSecret | Synchronous | default ||
| Applications.Connector/extenders | LIST/GET/PUT/PATCH/DELETE | Synchronous | default  ||
| Applications.Connector/extenders | POST ListSecret | Synchronous | default  ||
| Applications.Connector/mongoDatabases | LIST/GET/PUT/PATCH/DELETE | Synchronous | default ||
| Applications.Connector/mongoDatabases | POST ListSecret | Synchronous | default  ||
| Applications.Connector/rabbitMQMessageQueues | LIST/GET/PUT/PATCH/DELETE | Synchronous | default  ||
| Applications.Connector/rabbitMQMessageQueues | POST ListSecret | Synchronous | default  ||
| Applications.Connector/redisCaches | LIST/GET/PUT/PATCH/DELETE | Synchronous | default  ||
| Applications.Connector/redisCaches | POST ListSecret | Synchronous | default  ||
| Applications.Connector/sqlDatabases | LIST/GET/PUT/PATCH/DELETE | Synchronous | default ||
| Applications.Connector/sqlDatabases | POST ListSecret | Synchronous | default  ||

**Comment by jkotalik** [comment]
Current timeouts in Deployment Engine:
- Default retry timeout for resource deployment - retries requests 50 times, each with a 15 second timeout. Deployments will fail after 12.5 minutes on a resource. Continues to retry on 5xx errors.
- Default request timeout - will need to look into timeout policy for UCP as I think that ultimately dictates the timeout

Need to get more info on more timeouts, will get back to you. I don't think there is one by default.

**Comment by jasonviviano** [comment]
@youngbupark  do most of these not have a `Async operation retry condition` or we just don't know?

**Comment by youngbupark** [comment]
> @youngbupark do most of these not have a `Async operation retry condition` or we just don't know?

`Async operation retry condition` is applicable only for `Asynchronous` API types.
