### ISSUE TITLE
[DOCS] Stale VSCode extension link

### ISSUE THREAD

**Issue by willtsai** [radius-project/docs#195]
**Observed behavior**
The [Radius VSCode extension](https://radapp.dev/getting-started/install-cli/#2-install-custom-vscode-extension) link on this page is incorrect: https://radapp.dev/user-guides/tutorials/webapp/#prerequisites

**Desired behavior**
Should direct to the new page instead: https://radapp.dev/tooling/vscode/

**OS/rad version**
MacOS
```
RELEASE     VERSION      BICEP     COMMIT
0.12.0-rc1  v0.12.0-rc1  0.7.14    484ae03c8cd1dc7bb7a206836d4cd4adef18fc0d
```

**Screenshots**

**Additional context**

**Comment by emily-potyraj** [comment]
triage notes: @jasonviviano can you please help make this change and also please check everywhere else we link to the extension in prereq blurbs? thanks

**Comment by AaronCrawfis** [comment]
@willtsai please use edge.radapp.dev instead of radapp.dev, the current radapp.dev experience is very out of date, whereas edge.radapp.dev is what we're shipping for 0.12

**Comment by AaronCrawfis** [comment]
Closing as no-repro as edge docs have correct link

**Comment by emily-potyraj** [comment]
reopening 
- the tutorial's prereq section currently links to `https://edge.radapp.dev/getting-started/#setup-vscode`, which is a section name that doesn't exist
- still using this issue to scrub all our prereq blurbs for extension links 

relates to https://github.com/project-radius/radius/issues/3090

**Comment by jasonviviano** [comment]
Closing since the current tutorial in edge has a link to the correct section in getting-started `({{< ref "getting-started#install-vs-code-extension-optional" >}})`

PR: https://github.com/project-radius/docs/pull/227
