### ISSUE TITLE
Add more information on "Radius Extension"

### ISSUE THREAD

**Issue by kachawla** [radius-project/docs#198]
"Download Radius extension" link at https://edge.radapp.dev/getting-started/ isn't explicit about what does the Radius extension supposed to be used for. Would help to provide a link to relevant documentation here.

**Comment by emily-potyraj** [comment]
@jasonviviano can you please make this change while you're making the other couple link changes for the extension? thanks
(#195)

**Comment by emily-potyraj** [comment]
triage note: committed for v0.12

**Comment by jasonviviano** [comment]
Closing for PR: https://github.com/project-radius/docs/pull/227
