### ISSUE TITLE
[Doc] tutorial: value for `properties.environment` does not align with the the env name configured in the previous page

### ISSUE THREAD

**Issue by willtsai** [radius-project/docs#205]
**Observed behavior**

In the bicep file in this instruction that users will copy-paste, the value for `properties.environment` does not align with the the env name configured in the previous page, thus forcing the user to either have to make the edit or else missing it completely.

https://edge.radapp.dev/getting-started/tutorial/frontend/#define-a-radius-application-in-a-bicep-file

**Desired behavior**

the value for `properties.environment` should be `webapp-tutorial-environment` instead of `environment` to prevent user error.

**OS/rad version**

MacOS

```
RELEASE     VERSION      BICEP     COMMIT
0.12.0-rc1  v0.12.0-rc1  0.7.14    484ae03c8cd1dc7bb7a206836d4cd4adef18fc0d
```

**Screenshots**
Current:
<img width="646" alt="image" src="https://user-images.githubusercontent.com/28876888/180582534-f6b7c37c-e1c9-4fa0-8db5-153d71dfc226.png">

Desired:
```bicep
import radius as radius

param environment string

param location string = resourceGroup().location

resource app 'Applications.Core/applications@2022-03-15-privatepreview' = {
  name: 'todoapp'
  location: location
  properties: {
    environment: webapp-tutorial-environment
  }
}
```

**Additional context**

**Comment by willtsai** [comment]
same thing in [this section](https://edge.radapp.dev/getting-started/tutorial/frontend/#add-a-container-component)

<img width="685" alt="image" src="https://user-images.githubusercontent.com/28876888/180582739-54d263be-0772-49a2-afb6-303843880c33.png">

**Comment by emily-potyraj** [comment]
@Reshrahim can you please take a look at this one? thanks

**Comment by Reshrahim** [comment]
I believe the param is auto-injected as environment when the bicep file is deployed. 
@jkotalik - Do you know if a user can explicitly mention the environment name here so that it gets precedence over the auto-injection?

**Comment by jkotalik** [comment]
Few clarifying points:
- `environment` refers to the environment ID, not the environment name. So if you were to use  `environment: webapp-tutorial-environment`, that would cause failures in deployment eventually. We should make this crystal clear that the environment is an ID rather than a name.

The user can use their own environment ID instead of the one populated by default with either passing a parameter in for the environment ID (which can be environment, we won't override it if one is passed in by the user).

**Comment by Reshrahim** [comment]
How can a user know the environment id after initializing the environment?

**Comment by willtsai** [comment]
> Few clarifying points:
> 
> * `environment` refers to the environment ID, not the environment name. So if you were to use  `environment: webapp-tutorial-environment`, that would cause failures in deployment eventually. We should make this crystal clear that the environment is an ID rather than a name.
> 
> The user can use their own environment ID instead of the one populated by default with either passing a parameter in for the environment ID (which can be environment, we won't override it if one is passed in by the user).

@jkotalik Ah! This might explain why my deployment fails as observed in https://github.com/project-radius/docs/issues/207

**Comment by jkotalik** [comment]
> How can a user know the environment id after initializing the environment?

The goal is to make it so users don't have to know what the environment ID is, as it's a long resource ID. I don't think we have a great way of getting the environment ID today, maybe `rad environment show` exposes it? I don't know off the top of my head.

**Comment by emily-potyraj** [comment]
@Reshrahim what's our current thinking on whether we want to make a change in the tutorial around this?

**Comment by Reshrahim** [comment]
We have added information on the auto-injection of the environment parameter - https://edge.radapp.dev/getting-started/tutorial/frontend/#define-a-radius-application-in-a-bicep-file
