### ISSUE TITLE
[Doc] Tutorial env initialization instructions are clunky

### ISSUE THREAD

**Issue by willtsai** [radius-project/docs#206]
**Observed behavior**

I found myself getting lost and having to re-orient myself quite a bit to get through these instructions, especially for Step 2. 

https://edge.radapp.dev/getting-started/tutorial/tutorial-env/#initialize-a-radius-environment

**Desired behavior**
Might I suggest the following:

1. Prescribe a namespace for the reader to use, much like how one is suggested in Step 3 for env name.
2. Introduce Step 2 by telling the user they need to select `Y` when prompted to add an Azure Provider. Then walk them through each prompt to enter in all the correct Azure configurations.
3. The Service Principal step was most tedious, imo. After doing all the Azure stuff in the steps above, the CLI should give you the option of creating the SP on your behalf (much like how the RGs are set up) and then automatically grab the `appId`, `password`, etc. that's needed to complete the task. Since i didn't have an SP ready, I had to `ctrl+C` out, scroll up to copy and run the suggested command prompt to great the SP, and then redo all those Azure steps, but have to scroll up to get the SP information that I suspect most customers will miss. 
4. Step 3 looks good and works fine.

**OS/rad version**
MacOS

```
RELEASE     VERSION      BICEP     COMMIT
0.12.0-rc1  v0.12.0-rc1  0.7.14    484ae03c8cd1dc7bb7a206836d4cd4adef18fc0d
```

**Screenshots**

**Additional context**

**Comment by emily-potyraj** [comment]
committing to at least take another review of this language

**Comment by Reshrahim** [comment]
The service principal creation experience will be revisited in 0.13 to be less tedious.
