### ISSUE TITLE
[docs] stale links in tutorial

### ISSUE THREAD

**Issue by willtsai** [radius-project/docs#209]
**Observed behavior**
The radius-cli and vscode extension links (i.e. https://edge.radapp.dev/getting-started/#install-radius-cli and https://edge.radapp.dev/getting-started/#setup-vscode) on this page are stale - https://edge.radapp.dev/getting-started/tutorial/#prerequisites

**Desired behavior**
That links should point to 

- https://edge.radapp.dev/getting-started/#install-rad-cli
- https://edge.radapp.dev/getting-started/#install-vs-code-extension-optional

**OS/rad version**
MacOS

```
RELEASE     VERSION      BICEP     COMMIT
0.12.0-rc1  v0.12.0-rc1  0.7.14    484ae03c8cd1dc7bb7a206836d4cd4adef18fc0d
```

**Screenshots**

**Additional context**

**Comment by willtsai** [comment]
Another one:

on page https://edge.radapp.dev/getting-started/tutorial/overview/, bullet point 2, [`frontend-route`](https://edge.radapp.dev/getting-started/tutorial/overview/#todoroute-httproute) should be https://edge.radapp.dev/getting-started/tutorial/overview/#frontend-route-httproute

**Comment by Reshrahim** [comment]
Thank you Will for going over the tutorial and reporting these issues :)
