### ISSUE TITLE
Re-enable tests for tutorials

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/docs#21]
See https://github.com/project-radius/radius/pull/1902/commits/b6f74af3061bb33e826b4c6aa2c02669cf956e62 for what was disabled

**Comment by emily-potyraj** [comment]
deployment tests are done: bicep code in samples repo is validated, create local env, ensure that tutorial template is deployable. 

still haven't built out e2e tests: actually doing PUTs

**Comment by nicolejms** [comment]
triage: duplicate
