### ISSUE TITLE
Pivot "Codespace" docs into "Devspaces" docs

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/docs#212]
Due to billing limitations we need to disable Codespaces. Let's pivot the current Codespaces docs into Devspaces to still leverage the tech.

**Comment by emily-potyraj** [comment]
triage note: let's hold off on this change for another day because we want to investigate the billing limitation a little further. Let's see if @jonvsm's clout can help us get some free codespaces :)

**Comment by amanbha** [comment]
triage notes: leaving it as proposed until we get confirmation for billing changes for codespace

**Comment by emily-potyraj** [comment]
not needed now that we have codespaces approval. yay!
