### ISSUE TITLE
add a note about why `location: 'global'` in the Tutorial

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#218]
maybe in this section? https://edge.radapp.dev/getting-started/tutorial/frontend/#define-a-radius-application-in-a-bicep-file

It's common (on every Radius resource) and will likely be an open question to users already familiar with Bicep. 

(downstream of Donovan's walk through)

**Comment by nicolejms** [comment]
triage: not blocking but should be updated.

**Comment by AaronCrawfis** [comment]
Added into description of template
