### ISSUE TITLE
Update CI/CD quickstart to do `rad install kubernetes` locally instead of `rad env init`

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/docs#223]
Makes it a little clearer what's happening, as there are no client side environment actions.

[AB#7094](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7094)

**Comment by Reshrahim** [comment]
Moving this to Team A as they are working through rad CLI improvements. Feel free to move this back if Team B needs to tackle.

**Comment by Reshrahim** [comment]
@AaronCrawfis - CI/CD quickstart uses rad init today for env creation. Do we still want to show the control plane installation separately?

**Comment by AaronCrawfis** [comment]
> @AaronCrawfis - CI/CD quickstart uses rad init today for env creation. Do we still want to show the control plane installation separately?

Yes, because in production CI/CD systems there will need to be more control over each step in the pipeline. Most users will want to manage environments in clusters with existing installations.

**Comment by AaronCrawfis** [comment]
Updated
