### ISSUE TITLE
Basic debugging instructions for tutorial/any rad app

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/docs#226]
We need to help users debug their applications and environment in case of issues. 
There are various Radius system involved in deploying an application - would be good to tell users "What logs to check if you are encountering x type of issue)

**Comment by AaronCrawfis** [comment]
Love it! This will make for a great page. We should update https://edge.radapp.dev/reference/troubleshooting-radius/ with this content

**Comment by amanbha** [comment]
triage notes: committed for 0.12

**Comment by emily-potyraj** [comment]
example for a situation where a user might like to grab logs: 
https://github.com/project-radius/radius/issues/3304

if an example is needed on this page

**Comment by emily-potyraj** [comment]
it'd be great if this troubleshooting guide could also include an example of grabbing ARM event logs like in https://github.com/project-radius/radius/issues/3344
