### ISSUE TITLE
Add Dapr - Quickstarts resource list extra columns

### ISSUE THREAD

**Issue by bjoginapally** [radius-project/docs#229]
**Observed behavior**
On executing rad resource list --application dapr-tutorial. the output has resource and type columns only.

**Desired behavior**
Docs should be updated to inlcude only resource and type columns. Remove the additional columns

**OS/rad version**
rad version
RELEASE     VERSION      BICEP     COMMIT
0.12.0-rc1  v0.12.0-rc1  0.7.14    484ae03c8cd1dc7bb7a206836d4cd4adef18fc0d

**Screenshots**
![Screen Shot 2022-07-22 at 12 03 42 PM](https://user-images.githubusercontent.com/99223262/180506494-dd1b1dda-d681-4743-94a3-791031a40e1b.png)

**Additional context**
link to page: https://edge.radapp.dev/getting-started/quickstarts/dapr-quickstart/add-dapr/

**Comment by nicolejms** [comment]
triage: @AaronCrawfis to verify this is still an issue
