### ISSUE TITLE
Document application name limitation under known issues

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/docs#234]
As per https://github.com/project-radius/radius/issues/3287, a user cannot use the same application name across two different environments in the same cluster. This is a known limitation in .12 and should make sure we capture this information in docs in two places

1. Tutorial step - Swap the connector resource (User might initialize a sec env with an azure cloud provider in the same cluster and might use the same application name )
2. Known limitations page

**Comment by AaronCrawfis** [comment]
For 2), radius-project/core-team#611 adds a known limitation on this naming conflict.

For 1) we should make sure the instructions state to use the same environment and not to create another one.

**Comment by Reshrahim** [comment]
For 1) if we ask the users to have one environment all through the tutorial, we should call out azure pre-requisites as must have's

**Comment by amanbha** [comment]
triage notes: committed for 0.12
