### ISSUE TITLE
Make tutorial samples downloadable from docs instead of cloning samples repo

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/docs#236]
Right now, we have 450 people in our preview (number of people in the Teams team), but only 80 people in our GitHub org. When we send out the announcement they're going to land in the tutorial and 370 of them will need to request access. This is currently a manual process that requires one of the GitHub admins (me/Emily/Aman) to add them to the GitHub team.

For now I think the tutorial should be self-contained within the docs repo, and for the reference apps and quickstarts we can continue linking off to the GitHub org while we figure out a better self-service way to access GitHub.

**Comment by amanbha** [comment]
triage notes: not a blocker for 0.12.

**Comment by AaronCrawfis** [comment]
Completed as part of https://github.com/project-radius/docs/pull/239
