### ISSUE TITLE
Revisit the tutorial instructions 

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/docs#238]
[AaronCrawfis](https://github.com/AaronCrawfis) [1 hour ago](https://github.com/project-radius/docs/pull/224#discussion_r938079659) • 
One other thing to think through is the change of having the user write/copy code and instead just read code. Usually with tutorials you want the user to write or copy/paste code to better learn and understand how the tooling/features work. Scrolling through code and reading doesn't provide the same level of concept teaching in my opinion. We should have users write/copy code to learn how Bicep autocomplete and validation works instead of providing the complete sample at the beginning. Complete samples at the beginning are what reference apps are for.

Definitely want to hear the thoughts of https://github.com/orgs/project-radius/teams/radius-pm to see how others feel.

@[Reshrahim](https://github.com/Reshrahim) Reshrahim [1 hour ago](https://github.com/project-radius/docs/pull/224#discussion_r938101516)
I believe we decided to move away from teaching bicep as per the issue - https://github.com/project-radius/docs/issues/100

The goals of the tutorial that we decided on are

Enough knowledge to map your own application in Radius
Achieve portability via connectors between your local and cloud environments
Understand the separation of concerns for the different personas involved in a deployment
We also had feedback from Donovan to provide instructions on how they can replace the bicep code with their own containers and resources which is tracked here - https://github.com/project-radius/docs/issues/233

I guess, new users would do a copy and paste of the tutorial anyways. They wouldn't want to write the app components unless they want to build their own application.

@[AaronCrawfis](https://github.com/AaronCrawfis) AaronCrawfis [1 minute ago](https://github.com/project-radius/docs/pull/224#discussion_r938148902)
I guess, new users would do a copy and paste of the tutorial anyways. They wouldn't want to write the app components unless they want to build their own application.

There's still value in copying & pasting. You learn and add each piece individually, learning that particular concept instead of seeing everything together all at once and running rad deploy

**Comment by AaronCrawfis** [comment]
Decided offline from feedback to stick with download and review instead of copy/paste
