### ISSUE TITLE
Inner loop -- duplicated pages for local dev envs

### ISSUE THREAD

**Issue by ihood** [radius-project/docs#246]
[This page](https://edge.radapp.dev/author-apps/inner-loop/) has two children pages about how to run a local dev environment. I think one of these pages should be removed.

![Screen Shot 2022-08-04 at 2 43 53 PM](https://user-images.githubusercontent.com/71398878/182958171-dca5f84c-da4c-4638-979d-ac683a99c741.png)

**Comment by jasonviviano** [comment]
Fixed with: https://github.com/project-radius/docs/issues/272
