### ISSUE TITLE
Document instructions to convert sample app to an user app

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/docs#269]
Container/resources - explain how they add their own container /mongo db 

[AB#7098](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7098)

**Comment by AaronCrawfis** [comment]
Actionable items:

- More cross-linking into product feature pages in the tutorial
- Add a "go do" at the end of the tutorial to update the tutorial definition for your own app

**Comment by nicolejms** [comment]
triage: moving to v0.14

**Comment by AaronCrawfis** [comment]
This is covered through the new set of quickstarts
