### ISSUE TITLE
edge docs don't contain documentation for installing a specific version of Radius

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#277]
edge only seems to include instructions for latest stable and edge: https://edge.radapp.dev/getting-started/

v0.11: https://radapp.dev/getting-started/install-cli/#install-a-specific-version

I think we should pull the examples we had in v0.11 into some page in the v0.12 docs.

**Comment by emily-potyraj** [comment]
triage notes: not a blocker for v0.12, but let's make this change when we get the chance. proposed for v0.13.

**Comment by AaronCrawfis** [comment]
Current versioning strategy is we support only stable and edge. Once we support n-1 versions later on we can revisit this one
