### ISSUE TITLE
Update `redis` connector docs to indicate `connectionString()` does not work

### ISSUE THREAD

**Issue by mhaveliwala1** [radius-project/docs#282]
Right now, there is a bug that is stopping `connectionString()` from working for `redis` connectors. As a result, for 0.12 we will need to build connection strings using the `host` and `port` properties. So, it would be good to change those properties to required in the docs and remove `connectionString()` as a supported method for redis connectors.

**Comment by mhaveliwala1** [comment]
https://edge.radapp.dev/reference/resource-schema/connector-schema/cache/redis/ is where these docs currently live

**Comment by kachawla** [comment]
Issue to support connection string in next release https://github.com/project-radius/radius/issues/3352

**Comment by AaronCrawfis** [comment]
We should also make sure to document this at https://edge.radapp.dev/reference/limitations/
