### ISSUE TITLE
Add search bar to Radius docs page

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#29]
It would be useful to have a way to search across https://radapp.dev/ 

[AB#983](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/983)

**Comment by AaronCrawfis** [comment]
Easy to do with Algolia, but we do have an issue of the Algolia crawler needing to auth to the website in order to crawl it. Will look into how to support this.\ with AAD auth

**Comment by AaronCrawfis** [comment]
Crawler doesn't appear to support AAD Auth so we would need to send all page data to Algolia via the API at build time https://www.algolia.com/doc/guides/sending-and-managing-data/send-and-update-your-data/
