### ISSUE TITLE
rad deploy parameters should be documented in a more visible place

### ISSUE THREAD

**Issue by rynowak** [radius-project/docs#304]
We should make the guidance about **how** to use parameters and **when** to use parameters more visible. Ideally this could be a quickstart.

Right now the only way to find out about parameter support is through the CLI help, or this page https://edge.radapp.dev/reference/cli/rad_deploy/

Thanks @sylvainsf for the find

[AB#7109](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7109)

**Comment by sylvainsf** [comment]
Additionally there aren't any examples of actually using the parameters in your bicep, and the linked documentation to parameter files doesn't have info on it either.
