### ISSUE TITLE
Add essential quickstarts for a new user to deploy their own application on Radius

### ISSUE THREAD

**Issue by rynowak** [radius-project/docs#310]
## Summary

For Radius we're missing a lot of the basic information that should be part of a user's learning path when they pick up Radius. A good way to think about this is that the tutorial for Radius is a great intro but users won't retain the information completely after working through it. 

We want to have documentation that's more optimized for quick reference.

Some examples of a guides that hit the right level: 

- https://docs.acorn.io/authoring/containers 
- https://kubernetes.io/docs/tasks/
- https://www.nomadproject.io/docs/job-specification

----

This list is focused on developer/application manifest authoring since this is critical on the onboarding path. Mostly these are related to compute + networking since that's the starting point for developers.

## Basics

- [x] #306
- [x] #308
- [x] #307
- [ ] Add a quickstart showing how publish a port (route)
- [ ] Add a quickstart showing how do service discovery for HTTP (routes/env-vars)
- [ ] Add a quickstart showing how listen for public traffic for HTTP
- [ ] Add a quickstart showing how to set a hardcoded hostname for public traffic for HTTP
- [ ] Add a quickstart showing how to use path-based routing for public traffic for HTTP
- [ ] Add a quickstart showing how to override the commandline args of a container
- [ ] Add a quickstart showing how to add a sidecar to a container
- [ ] Add a quickstart showing how mount an ephemeral volume
- [ ] Add a quickstart showing how to set liveness and readiness probes
- [ ] Add a quickstart showing how configure image pull behavior
- [ ] Add a quickstart showing how use parameters to set the container image
- [ ] Add a quickstart showing how set custom environment variables using values from connectors
- [ ] Add a quickstart showing how set environment variables with secrets
- [ ] Add a quickstart showing how set resource requests/limits
- [ ] Add a quickstart showing how to configure manual scaling

## Guides

In addition we should author guides approaching how users learn Radius starting from an understanding of docker-compose or Kubernetes

- [ ] Learning Radius for the docker-compose developer
- [ ] Learning Radius for the Kubernetes developer

[AB#7099](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7099)

**Comment by AaronCrawfis** [comment]
Closing as we have a new documentation framework that tracks a set of how-to guides and tutorials.
