### ISSUE TITLE
Docs: Create a converting to Radius from Kubernetes page

### ISSUE THREAD

**Issue by rynowak** [radius-project/docs#316]
See: https://github.com/project-radius/radius/issues/3066#issuecomment-1193394568

I claimed that it's "pretty easy" to convert from Kubernetes manifests to Radius. However, that's only really true for someone who already knows Kubernetes and Radius pretty well.

We should write a guide that's targeted at porting from Kubernetes -> Radius with an audience of developers at the 100-200 level in Kubernetes knowledge. We can vet this guidance by looking at existing k8s samples like the Dapr quickstarts.

[AB#7091](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7091)

**Comment by nicolejms** [comment]
triage: removing iteration

**Comment by Reshrahim** [comment]
closing as duplicate of radius-project/radius#526
