### ISSUE TITLE
Mention how to build a resource ID for table storage in Dapr statestore docs

### ISSUE THREAD

**Issue by rynowak** [radius-project/docs#317]
Talking about [this page](https://edge.radapp.dev/reference/resource-schema/connector-schema/dapr-schema/dapr-statestore/)

As a general point, we should do a better job talking about how to find resource IDs for resources that are provisioned outside of Bicep. I do this in the portal with "Show JSON View" which gives you a copy-field for the resource ID.

For table storage this is a little more tricky because the resource ID we need is that of a table, which actually a level-3 resource. 

If you know the resource ID of the storage account already, then you need to append to it like the following. I haven't seen a way to find this info via the UI.

```txt
account: ...providers/Microsoft.Storage/storageAccounts/<accountname>
table: ...providers/Microsoft.Storage/storageAccounts/<accountname>/tableServices/default/tables/<tablename>
```

[AB#7095](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7095)

**Comment by nicolejms** [comment]
triage: move to v0.13

**Comment by nicolejms** [comment]
triage: removing from iteration

**Comment by AaronCrawfis** [comment]
Closing as we're moving away from resource-backed Links and instead using Recipes
