### ISSUE TITLE
Automate upmerge process

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/docs#326]
Click a button and start the upmerge process

[AB#7103](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7103)

**Comment by jasonviviano** [comment]
Will most likely be tackle post public release.

**Comment by Reshrahim** [comment]
completed by https://github.com/radius-project/docs/pull/1106
