### ISSUE TITLE
Delay access to mongodb in sample until first request

### ISSUE THREAD

**Issue by jkotalik** [radius-project/docs#33]
We should delay https://github.com/Azure/radius/blob/main/docs/content/user-guides/tutorials/webapp/code/src/routes/api.ts#L23 until the first request comes in as the db may not be available yet (even though it is running).

**Comment by rynowak** [comment]
We also just might want to open the connection on every request to simplify this. Right now the way this code is written, it will never recover if the connection breaks.

**Comment by AaronCrawfis** [comment]
Closed as part of https://github.com/project-radius/samples/pull/35
