### ISSUE TITLE
simplify the Steps section of the Tutorial main page 

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#359]
https://radapp.dev/getting-started/tutorial/#steps

Feedback from usability sessions:
- user 1: Steps section on main page are hard to read and 3rd item feels like an orange among apples. Also he expected the links on those cards to be tutorial links, but they actually link out to general documentation. 
- user 2: Simplify the Steps section on the main page to make it more likely people will read it. 
- user 3: Steps section is too long and links out to other complex sections give users a way to shoot themselves in the foot
 

[AB#5239](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5239)

**Comment by AaronCrawfis** [comment]
Closing as we completed the migration to "first app experience"
