### ISSUE TITLE
user feedback: route concept is an unapproachably complex Day0 experience

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#360]
During the Tutorial, many usability testers remarked that they were surprised to see a route resource when we first introduce it in the app diagram:
![image](https://user-images.githubusercontent.com/36576265/196121603-6599eec5-abe3-4401-9f1f-ba412825c3e0.png)
https://radapp.dev/getting-started/tutorial/

- User 1: "When I saw this route resource, I took a mental note that I have to figure out later how gateway and route are connected since gateway usually manages the route. I immediately see it as a way Radius is 'different' since I usually wouldn't think of frontend route as a separate thing. Some people might be concerned "How hard is it to implement? And for people that grok this mental model, they'll have questions about its implications: How reusable are these pieces? How does load balancing map into it? I recommend you eventually have more networking quickstarts, like for load balancing.
- User 2: "I'm not sure what this HTTP route is for. Why can't the gateway talk directly to the frontend container?"
- User 3:  They were surprised there was a route resource in addition to the gateway resource (app diagram). "It would be nice if the route existed by default. It was a little surprising that the frontend had its own route."
- User 4: "It seems like you _really_ want people to go click on the HTTP Route link. I did, and I still don't know why it's a separate resource and now also wonder whether it's our own YAML format or Bicep. 

And later in the tutorial, in the "Container and route" section, the route concept again provided more confusion than clarity.
![image](https://user-images.githubusercontent.com/36576265/196121860-b8a102be-a99f-4ca0-83d8-210c9c69f338.png)
https://radapp.dev/getting-started/tutorial/application/#container-and-route

- User 1: `provides: frontendRoute.id` -- "no idea how I'd set that"

[AB#5238](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5238)

**Comment by AaronCrawfis** [comment]
This has been addressed as part of the new first app experience
