### ISSUE TITLE
Tutorial: put the app diagram adjacent to the app code

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#361]
The app diagram is currently on the tutorial's home page. 
https://radapp.dev/getting-started/tutorial/

Multiple usability test users remarked they would like to have the diagram adjacent to the example code on
https://radapp.dev/getting-started/tutorial/application/

I personally vote to move the whole App Overview section to that later phase of the tutorial, but open to discussion if we want to have duplicative info in some shape. 
______________

User 1: Move the App Overview section and its diagram from the Tutorial main page to the Author an app page so the diagram is adjacent to the Bicep code we're walking through. 

User 2: Add app diagram to Author app page

[AB#5240](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5240)

**Comment by AaronCrawfis** [comment]
This has been addressed as part of the new first app experience
