### ISSUE TITLE
Tutorial: move "The Radius Mindset" blurb to live outside the tutorial

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#362]
https://radapp.dev/getting-started/tutorial/#the-radius-mindset

We heard in multiple usability study sessions that this section doesn't fit with the flow of the tutorial. If we like this content, it likely has a place elsewhere in the docs _outside_ the tutorial. 

There is a broader conversation we should have about whether the tutorial is **only** for devs (instead of solving for two personas). 

Regardless, this section needs reevaluation to see if we can get it integrated a bit more into the flow of the tutorial. 

____________

- User 1: "It's too confusing to say we're going to be pretending to be two different users."
- User 2: "Should we move it to another page since it's not necessarily about teaching people how the tech works?"
- User 3: "That's a lot of words that aren't "anchored" to anything yet. It's an orthogonal concept."
- User 4: 
  - "What this section is saying is super important. The current state is that nobody is going to have all the permissions to deploy all the pieces described in Radius- they need 8 people in the room to do all the things. If you guys can solve the permissions pain points of separation of concerns, it's a huge thing for enterprises, especially for orgs that have shipped existing org structures from the on-prem world into the cloud. But this section's audience is for a 3rd party who's trying to deliver their customer's products to the cloud or for central groups like solution leads - not for developers. 
  - And even if devs **are** thinking about separation of concerns, then they're probably thinking of it from the perspective of building the app, like "he owns the database, and she owns the indexing service." So they're not thinking about the operationalization and the separation of concerns in the delivery of the app. 
  - Plus, any mindset pieces that are important for devs (tutorial audience) to know should be above the app description."

[AB#5228](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5228)

**Comment by AaronCrawfis** [comment]
Closing as we completed the migration to "first app experience"
