### ISSUE TITLE
install Rad CLI: change order of platform tabs

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#364]
**current state**
https://radapp.dev/getting-started/#install-rad-cli
<img width="647" alt="image" src="https://user-images.githubusercontent.com/36576265/195499423-419c6680-12e7-4910-b6f9-917ffcd54c1a.png">

Windows is the first listed platform. 

Usability study users reported that, beyond having an infrequently-chosen item first, we also are coming across as Microsoft-centric by having Windows listed first. 

**desired state**
Put Mac option first. 

_________
btw, one user even went as far as to say: 
> If Radius really wanted to seem open-source, Radius would include nothing about Powershell here. "Powershell" sticks out like a sore thumb." 

[AB#5510](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5510)

**Comment by AaronCrawfis** [comment]
This has been completed
