### ISSUE TITLE
Tutorial: add a diagram to the Swap Connector page

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#365]
https://radapp.dev/getting-started/tutorial/3-tutorial-connector/

This page currently counts on the user remembering the app diagram from a couple pages previously to understand what the swap is and how the new resource fits in. 
https://radapp.dev/getting-started/tutorial/
<img width="581" alt="image" src="https://user-images.githubusercontent.com/36576265/195501375-a4bf66ff-a206-4a47-b251-ef5a9f553e94.png">

[AB#6632](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/6632)

**Comment by AaronCrawfis** [comment]
This has been addressed as part of the new first app experience
