### ISSUE TITLE
make a plan for how we will convey that Bicep isn't Azure-specific anymore

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#370]
We had a usability tester share that they had the preconception that Bicep is Azure-specific, so it was a surprise for them to see EKS listed as a supported cluster. 

Many of our users who are aware of Bicep will also have this initial mental model that Bicep == Azure. 
How can we convey that, with Radius, Bicep is no longer Azure-specific? 

[AB#7104](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7104)

**Comment by AaronCrawfis** [comment]
Closing as this is being covered separately in OSS readiness
