### ISSUE TITLE
Update concept docs to better define apps/environments and how they relate to Kubernetes

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#373]
## Overview
Users are looking for clearer language about how Radius environments, applications, and app resources relate to each other. There is definitely a docs-side component here to better educate users about Radius concepts, but we should also reflect on whether there's opportunity to simplify our concepts so users have less complexity to learn grok before they can get going in Radius.
- Relates to https://github.com/project-radius/radius/issues/4267 

## Current state of docs
Some of our current language includes: 
1. "The **application acts as the container** for all of your application services, infrastructure, and relationships." (from the [tutorial](https://radapp.dev/getting-started/tutorial/application/#application))
   - One user asked, "Do you really have to use the word 'container' when describing what the app is?" 
3. "The **largest circle you can draw around your resources** where names have meaning." (from the [app model concept page](https://radapp.dev/concepts/appmodel-concept/#defining-an-application))
4. "An application is **defined as a top-level `resource app`** in an instrastructure-as-code file" (from the [defining an application](https://radapp.dev/concepts/appmodel-concept/#defining-an-application) section of the Overview > App model page).

And we have other similar phrases across the docs. None of them clearly describes the fact that applications and their participating resources are all top-level resources in our app model. 

--> We should discuss the language we want to unify on more broadly to describe how Radius apps relate to our other Radius concepts. 

## Usability feedback 
- "Oh ok, in Radius an app is going to be a resource. I don't normally expect that."
- "After reading the App model concept page, I thought "application" would be the black boxes in that diagram. Is the env the red box?
![image](https://user-images.githubusercontent.com/36576265/196113116-0506559d-f2a1-4bd8-bd6e-1abf39dc565b.png)
https://radapp.dev/concepts/appmodel-concept/

- "The section title says "Application" [on the [Author app page of the Tutorial](https://radapp.dev/getting-started/tutorial/application/#application)], but the code seems like it's setting up an environment. Nothing about it really screams app to me, but I don't see container here. There's nothing here that defines what the user thinks of as **their** app.
![image](https://user-images.githubusercontent.com/36576265/196113670-d4d3a7d5-0756-4b01-be7c-ed16c1913185.png)

- "If I'm doing the Tutorial as the first entry to Radius, I don't get the hint that Radius sits inside K8s until the "Initialize a Radius env" section. I was confused earlier why I had to create a Radius env if I was planning to deploy to Azure."
- "The hierarchy of Radius apps and resources could be clearer. Do Radius users need to know about Radius environments before deploying a Radius app? If so, you have to teach them about the relationship between the two beforehand." 

[AB#5237](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5237)

**Comment by AaronCrawfis** [comment]
This is complete: https://edge.docs.radapp.dev/guides/operations/kubernetes/resource-mapping/
