### ISSUE TITLE
Tutorial: adjust `env init` wording to make code and text match

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#374]
https://radapp.dev/getting-started/tutorial/init-environment/#initialize-a-radius-environment
In the Initialize a Radius environment we currently say in text
> Use the [rad env init kubernetes command](https://radapp.dev/reference/cli/rad_env_init_kubernetes/) to initialize a new environment into your current kubectl context:

but the command directly below is not identical
> rad env init kubernetes -i

In usability testing, it was suggested that the `-i` is an unexplained surprise in the code line, and the user doesn't know what it's for. 

Maybe just add a note about "`-i` for interactive mode" in the text somewhere? 
or use `-interactive` so it's self-documenting?

**Comment by AaronCrawfis** [comment]
I agree this is confusing. Thankfully `rad env init` is being deprecated in 0.15, in favor of `rad init`, which will be much more straightforward.

Closing as the tasked out work for `rad init` captures updating the docs.

**Comment by AaronCrawfis** [comment]
Nvm it's an easy fix
