### ISSUE TITLE
Tutorial: move the databases to be inside the app boundary

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#375]
In the app overview section we currently show the two database resources outside of the app boundary (the purple box)
<img width="731" alt="image" src="https://user-images.githubusercontent.com/36576265/195509223-9cdb9fc6-8d77-49ad-a127-df847ca204af.png">
https://radapp.dev/getting-started/tutorial/#application-overview

The setup might lead a reader to wonder why those resources aren't part of the app, even though we (the Radius team) would consider them to be. 

Additionally, this diagram also may be interpreted as the participating resources being child resources to the _todoapp_ application resource. 

[AB#5235](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5235)

**Comment by AaronCrawfis** [comment]
This has been addressed as part of the new first app experience
