### ISSUE TITLE
reconsider usage of the phrase "model an app"

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#376]
In several usability sessions, we got feedback that the word "model an app" might not be the most useful, enticing verb to describe what Radius can help people do. 

Some feedback about that verb: 
- User 1: "The word "model" is a turn off and doesn't feel like much value. From a strictly developer focus, they probably don't care about modeling the app because it's likely their code isn't hardened and "tried-and-true" yet."
- User 2: "I choke on the word 'model'. It makes it sound fake and architect-y. I think developers would prefer to see 'define' or 'build.'"

[AB#5241](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5241)

**Comment by AaronCrawfis** [comment]
This has been addressed as part of the new first app experience. We are also moving to "describe an app" as part of the application graph branding
