### ISSUE TITLE
check in the refresh of the Radius docs home page

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#381]
_Note: this issue tracks committing the change to the docs repo. Iteration of the wording is tracked in an internal ticket (https://github.com/project-radius/core-team/issues/341) since some suggestions so far contain customer names._

The landing page hasn't gotten a facelift in a while, and we've iterated on our messaging since then. 

Two places could use the update: 
1. docs: https://radapp.dev/
2. main Radius repo: https://github.com/project-radius/radius/blob/main/README.md

[AB#7105](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7105)

**Comment by AaronCrawfis** [comment]
Closing as there's a new homepage
