### ISSUE TITLE
"Before" state in Concepts page is verbose and Microsoft-y

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#382]
Our Concepts>Overview page currently has a section describing the pre-Radius "before" state. The section is called "Building cloud-native apps is too difficult today."
https://radapp.dev/concepts/overview/#building-cloud-native-apps-is-too-difficult-today

From usability testing: 
- User 1: "I'd skip that section and jump all the way down to the pseudo-sample section. ("Model applications as code"). Make it clear that the journey we're going to take the user on is _at least_ as simple as their current flow. Showing the complex enterprise before and after isn't enough."
- User 2: "This diagram feels very Microsoft-y, especially with PowerShell so prominent. I also suggests adding GCP to appear vendor neutral. Few orgs that have Azure + AWS don't also have GCP."

[AB#7106](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7106)

**Comment by jasonviviano** [comment]
Closing, restructuring in current docs makes this issue a bit dated and other issues track new concept page requirements.
