### ISSUE TITLE
add a "5 minutes to wow" path in our docs

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#383]
Currently, we have a 45-minute+ flow with our Radius Tutorial. 
https://radapp.dev/getting-started/tutorial/

The Tutorial is currently meant to be the first place we teach new users about the mechanics of how Radius works. However, we've gotten feedback from usability testers that it's unusual for have such a long tutorial as the first experience. 
- It asks a large time investment from the user
- It's heavy, technical info right away. Users have to wade through deep text about concepts before they see the "wow!" of Radius in action at all. 

Usability feedback
- "I wouldn't go through all this. It's a lot to process going param by param and putting it altogether. Devs need the quick flow to get started."
- "It's currently a major commitment to learn Radius before I try converting my own apps."
- "Radius needs a 5-min journey"
- "You won't capture people who are just messing around trying to see if Radius is for them."
- "The tutorial is in heavy learn mode. There's a lot of machinery."
- "Oh! I really have to buckle down here. It seems strange that you're presenting devs with a 45-minute flow first."
- "The tutorial needs framing on how long you expect it to take people. Right now you can only tell you're 'settling in for the big one' when you see the app diagram."

Relates to this older issue:
- https://github.com/project-radius/docs/issues/109

Also see Dapr's [Use Dapr API page](https://docs.dapr.io/getting-started/get-started-api/) for example "5 minutes to wow"

____________

Note: dev-side change to add simpler Day0 experience is here:
- https://github.com/project-radius/radius/issues/4267

[AB#5246](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5246)

**Comment by AaronCrawfis** [comment]
This has been addressed as part of the new first app experience
