### ISSUE TITLE
Clarify `location` property in first app experience

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#385]
## Overview 
Currently users see the `location` property in our very first code block in the tutorial, which demonstrates describing an app resource in Radius. 
![image](https://user-images.githubusercontent.com/36576265/196117069-93ac0ab2-9a00-493c-8306-b7b2e33d2c39.png)
https://radapp.dev/getting-started/tutorial/application/#application

It's been jumping out in usability sessions as a common point of confusion, distracting from the flow of learning about the Radius app resource itself. 

Note: this issue was opened based on feedback about the Tutorial, but we should consider whether there are other places in our docs we need to clarify the location property as well. 

## User feedback: 
- User 1: Add a note that the location property is a point-in-time implementation. Today, you're adding confusion to users by calling it out since it makes them wonder why we even need it since they have their cluster context and a Radius environment already setup. Also, the note about location in this Application section needs clarification. 
  - fyi, current state is: "The location property defines where to deploy a resource within the targeted platform. For self-hosted Kubernetes environments this value must be set to 'global'. See [Resource Schema](https://radapp.dev/reference/resource-schema/) for more info."
- User 2: Users won't understand how to set it. 
- User 3: `location: 'global'` is going to cause pain for 1P Microsoft because `global` location is verboten. 
- User 4: There's a lot of stuff I don't understand in this initial app code block, like `location: 'global'`

[AB#5247](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5247)

**Comment by AaronCrawfis** [comment]
Location has been removed
