### ISSUE TITLE
Tutorial: consider not showing the code of the mongo-container.bicep module

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#387]
A usability tester suggested that, if we really wanted to embrace Bicep, we might not dive into the contents of mongo-container.bicep. 

Two reasons to hide it from users: 
1. Demonstrate the simplified experience that Bicep brings here 
> I'd think that the Radius experience here would be "You can exec this with no parameters and it'll set a bunch of stuff for you. If you want to know the implementation details and settings, you can find them here...." 

2. Simplify the Radius onboarding expereince 
> Currently, exposing all the details of the mongo-container.bicep file opens more questions for the reader. For example, for `output connectionString string = 'mongodb://${name}:${port}/${name}?authSource=admin` makes me wonder if Radius sets this up for me."

[AB#5245](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5245)

**Comment by AaronCrawfis** [comment]
Closing as we switched to Recipes
