### ISSUE TITLE
Doc changes to help users grok the connectors concept faster

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#388]
Across usability testing, we had feedback about different places in the docs where users got confused about the connector concept and had trouble understanding what we were presenting. 
A couple suggested changes are below. 

### Suggestion 1: (Tutorial) rename `db` resource (which is a connector resource) 
We currently teach users about a Mongo connector resource, but the name of the resource is `db`, which adds to the confusion of new Radius users already trying to understand how connectors link up to their supporting resources. 
 
![image](https://user-images.githubusercontent.com/36576265/196126531-be88a12e-1f81-4aad-99af-c9bb7e870c4b.png)
https://radapp.dev/getting-started/tutorial/application/#mongo-connector

- User 1: "You need to clarify the connector resource code versus the database code."
- User 2: "The name `db` is confusing and makes people think it's the database itself, not the connector resource."

### Suggestion 2: (Concepts) Be clearer about the value of connectors on the Concepts Overview page.
- User 3: After talking through a point of confusion about connectors later, they remarked that "the [Overview page](https://radapp.dev/concepts/overview/) doesn't call out the benefits of Connectors (or Connections)."

### Suggestion 3: (Tutorial) introduce the value of connectors earlier in the tutorial 
We currently name a connector resource on the Tutorial main page, but we don't explain what it is or why it's valuable until the middle of the Tutorial.
- [Tutorial main page](https://radapp.dev/getting-started/tutorial/#application-overview): 
![image](https://user-images.githubusercontent.com/36576265/196129169-45e7571e-c8b9-4751-8840-56eed1552bf1.png)
- [Author app page](https://radapp.dev/getting-started/tutorial/application/#connectors)
![image](https://user-images.githubusercontent.com/36576265/196129340-1abacafe-eadd-4577-88b5-dc84d10bd5cc.png)

- User 4: "I wish the Connector description section was on the Tutorial main page so I could orient to the concept as early as possible" (The user felt this info would be useful in addition to anything about Connectors in the separate Concepts section.)

### Suggestion 4: (Tutorial) adjust links to better answer user's questions about connectors 
- User 5: "Neither of these links [in the [Connectors section of the Tutorial](https://radapp.dev/getting-started/tutorial/application/#connectors)] is the expected content. I would expect them to link to a connector concept page instead."
 
### Suggestion 5: (Tutorial) remove Mongo info from connectors section.
- User 6: "There's a [Containerized Mongo DB sub-section](https://radapp.dev/getting-started/tutorial/application/#containerized-mongo-db). It's in a section called "Connectors" where I'm trying to learn about Connectors. You're distracting me by telling me how to build a mongo module."

### Suggestion 6: (Tutorial) be more direct in showing how `db` connects to `frontend`
The current layout makes people scroll back up and try to piece it together themselves. Let's explain it more directly in the connector part of the page. 
![image](https://user-images.githubusercontent.com/36576265/196137833-e321032f-0066-4029-8671-3ae48781db8a.png)
https://radapp.dev/getting-started/tutorial/application/

[AB#5251](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5251)

**Comment by Reshrahim** [comment]
closing this as most of the feedback is in our old tutorial which has been revamped into the new first app experience
