### ISSUE TITLE
Doc changes to help users grok the value of Radius connections

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#389]
- "In the 'Connect to `db from `frontend` section, why does the https://radapp.dev/getting-started/tutorial/application/#connectors
- "Once the db connector is defined, you can reference it in the [connections](https://radapp.dev/concepts/appmodel-concept/) section of the frontend resource, as shown above." - change link to be for Connection header direct link. 
- topics that are Radius functionality that make the user curious about how useful / extensive they are: routes, connection strings
- Connection string clarity 
  - question that come to mine: how flexible is it? how limited is it? if I choose to use Radius, am I now limited to using connectionstrings for _everything_ (or can I use service principles)?
  - Does connection string mean connectionstring specifically, or is it more generic? 
  - The tutorial doesn't really talk about the auth part (e.g. Is it backed by a token?). Suggestion to add link to a page that talks more about how privileges work, eg. connector schema page. 

[AB#6633](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/6633)

**Comment by AaronCrawfis** [comment]
Addressed in https://github.com/project-radius/docs/pull/688
