### ISSUE TITLE
Tutorial: adjust MO from linking out so much to building a self-contained flow 

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#390]
We've gotten a fair amount of feedback during usability testing that we have A LOT of links in our tutorial. 
Sometimes we have links to content the user wasn't expecting, but the bigger issue is that we're prompting users to jump around a lot and to piece the explanation together themselves. 

Some user reflections: 
- User 1: 
  - "Having links to other pages encourages people to go down rabbit holes. Do you want that, or do you want them to stay on a golden path during the tutorial?"
  -  "I'm surprised to see so many concepts linked out when I thought I was deep in execution mode of the tutorial by now. You're putting a lot of text between the user and seeing Radius function. For example, when [telling](https://radapp.dev/getting-started/tutorial/init-environment/#initialize-a-radius-environment) the user how to initialize a Radius environment, these links are just leading me away from your lesson: "
     > Follow the prompts to install the [control plane services](https://radapp.dev/concepts/architecture/), create an [environment resource](https://radapp.dev/operations/environments/), and create a [local workspace](https://radapp.dev/operations/environments/workspaces/).
- User 2: 
  - "I wish you would stop linking out to other docs pages and put that info inline nicely. I don't want to read through a technical manual with 'follow all these links to piece it all together.'"
  - "An example of a nice tutorial is: https://github.com/IBM/CodeEngine/tree/main/thumbnail. They have one command paired with plenty of explanation text. And they have thoughtful explanations of what's going on. For example, that IBM tutorial says 'Let's pause here for a moment to understand what we just did...'."
 - User 3: 
   - "Ugh. I wish you would be more cognizant about sending me out to other pages so much." 
 - User 4: 
   - "[In the "Initialize a Radius environment" section] I don't know what any of these Radius concepts are yet. Was I supposed to have read the Concepts section before starting the Tutorial?" 

[AB#5231](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5231)

**Comment by AaronCrawfis** [comment]
This has been addressed in the new first app experience
