### ISSUE TITLE
notes for Tutorial changes downstream of cloud provider CLI changes

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#391]
(WIP) 
Suggest moving to 1 tutorial flow. Get to the end. It says Optional: add cloud provider to your cluster and do this extra step of swapping to an Azure resource. 

Tutorial changes: 
- change Prereqs list 
  - e.g. should "az CLI" be a req? If so, should it be first? Several usability testers remarked that they were surprised to see that item last in the list
- "If deploying to Azure, create or ensure access to an [Azure subscription](https://azure.com/) (optional - used in last tutorial step to deploy Azure resources)" - surprisingly 'choose your own adventure' when I'd prefer to be on a set path and not have to make decisions. 
- The tutorial will definitely be smoother once adding cloud providers is incremental and we don't have to talk about both options the whole time
- add azure cloud provider: would expect example on how to verify it's configured properly 
- consider expanding the CLI example on page for any interactive flow. 
  - eg. on the [initialize a radius env](https://radapp.dev/getting-started/tutorial/init-environment/#initialize-a-radius-environment) section, don't just say "follow the prompts" 

[AB#5229](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5229)

**Comment by AaronCrawfis** [comment]
Closing as we completed the migration to "first app experience"
