### ISSUE TITLE
add more context for `param environment string`

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#393]
Our docs currently have minimal explanation for this line, but users see it in every Radius bicep template. 
The only info about it today is on our [Limitations](https://edge.radapp.dev/reference/limitations/#environment-bicep-function-collides-with-param-environment-string) page:
![image](https://user-images.githubusercontent.com/36576265/196144059-f1f3579c-2556-46c2-8335-119f90cd3aa7.png)

During the tutorial, however, we leave users wanting more info about this line so they know what to do when building their own Radius apps. 

Many users encounter it for the first time in the [section](https://edge.radapp.dev/getting-started/tutorial/application/#application) describing the application resource in the Tutorial. Here's some of their feedback at that point: 
- "`param environment string` has no context."
- "`param environment string` - I don't know what this is or how it's used."
- "The first code block of the tutorial contains `param environment string`, making the user wonder how they will have to set the param, and the user may not even understand what environments are for yet. I wish you would either simplify the concept learning path or pull in info about temporary oddities from Limitations page."

[AB#5242](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5242)

**Comment by AaronCrawfis** [comment]
Added descriptions
