### ISSUE TITLE
Tutorial: add an explicit introduction to the environment concept

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#394]
and how it fits together with the other Radius concepts. 

Currently, if a user follows the Tutorial to learn about Radius, their experience is to go from [steps to initialize an env tactically](https://edge.radapp.dev/getting-started/tutorial/init-environment/) to seeing the `param environment string` in their first bicep template defining the app. 

Even something as simple as "Your app has to run somewhere. When you define your app, you say what env it runs in" could help bridge the gap.  

[AB#5244](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5244)

**Comment by AaronCrawfis** [comment]
Added introduction as part of first app experience
