### ISSUE TITLE
Image not loaded - WebApp Tutorial

### ISSUE THREAD

**Issue by ytimocin** [radius-project/docs#421]
Link: https://edge.radapp.dev/getting-started/tutorial/application/

![image](https://user-images.githubusercontent.com/5220939/201229868-027c4aae-99b2-4615-9456-4286b38780fb.png)

[AB#5033](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5033)

**Comment by AaronCrawfis** [comment]
Closed as part of https://github.com/project-radius/docs/commit/123f456afacf6ed8584986e07a0bf00b489d46e6
