### ISSUE TITLE
Unroll Languages section

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/docs#434]
We plan to only support Bicep, so we should unroll the languages section and make it a "Bicep" section instead. Perhaps we can even explore a "Tooling section" and add in the CLI.

[AB#5234](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5234)

**Comment by jasonviviano** [comment]
Closing, dedicated Bicep section already exists.
