### ISSUE TITLE
Update document for application-scope namespace

### ISSUE THREAD

**Issue by youngbupark** [radius-project/docs#438]
Parent feature - https://github.com/project-radius/radius/issues/3740

[AB#5305](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5305)

**Comment by AaronCrawfis** [comment]
I believe we'll need to update:

- https://edge.radapp.dev/operations/platforms/kubernetes/resource-mapping/
- https://edge.radapp.dev/reference/resource-schema/core-schema/container-schema/
- https://edge.radapp.dev/reference/resource-schema/core-schema/environment-schema/
