### ISSUE TITLE
add output of `rad init --dev` to First Deployment page

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#440]
We might also want to create a shortcode in our docs for example CLI output. 

See Aaron's suggestion
> Some inline html should do the trick. Or we could write a dedicated shortcode if we don't want raw HTML in the pages
```
<details>
    <summary>Details</summary>
    Something small enough to escape casual notice.
</details>
```
https://github.com/project-radius/docs/pull/425/files/44b75ef5bb7627f9bb97f2733ee2d4206d5899f3#r1042498090

[AB#5452](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5452)

**Comment by AaronCrawfis** [comment]
This has been addressed as part of the new first app experience
