### ISSUE TITLE
Web App Tutorial doc update requested for Swap Link 

### ISSUE THREAD

**Issue by lakshmimsft** [radius-project/docs#443]
Under https://github.com/project-radius/docs/blob/edge/docs/content/getting-started/tutorial/3-tutorial-link/_index.md
the section:
```
Update the link definition
Lastly, update the link definition to use a resource reference instead of manually defining the connection string by replacing secrets: {...} with resource: mongo.outputs.cosmosDatabaseId:
```
does not mention updates to other fields:
    mode: 'values'
    host: mongo.outputs.name
    port: mongo.outputs.port

As a user following instructions for the first time, I was about to update only the secrets as mentioned above, in the app.bicep file. 
We could add more information to the section/request user to replace the link section

[AB#5459](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5459)

**Comment by jasonviviano** [comment]
I can take this on.

**Comment by AaronCrawfis** [comment]
Closing as we moved to a new first app experience
