### ISSUE TITLE
add instructions for deleting Kubernetes resources

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#445]
Could be part of `rad application delete` story somehow or added as a separate topic somewhere in our docs. 
Flows like the quickstarts and tutorial should be able to reference a link to this How to info. 

https://radapp.dev/reference/cli/rad_application_delete/

[AB#5465](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5465)

**Comment by Reshrahim** [comment]
completed by https://github.com/project-radius/docs/pull/655
