### ISSUE TITLE
move note about Radius CLI install requiring `sudo` to CLI instead of docs

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#446]
Currently in our docs we note this requirement: 
> You may be prompted for your admin password (`sudo`) during installation, as the installer places the `rad` binary under `/usr/local/bin`. If you are unable to use `sudo`, you can install the rad CLI to another directory by setting the `RADIUS_INSTALL_DIR` environment variable with your desired install path.

We do want to give users this info somewhere, but we should reflect on whether the note should be docs-side or code-side. 

[AB#5466](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5466)

**Comment by AaronCrawfis** [comment]
Not planned
