### ISSUE TITLE
add recipes workflow into the Getting Started page

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#447]
Content is drafted in this side branch: 
https://github.com/project-radius/docs/blob/emily/getting-started-plus-recipes/docs/content/getting-started/first-application/_index.md

It was reviewed as part of creating our new, simple Getting Started workflow. 
We removed the recipes part (sections number 5 and 6 on that page) for now because the functionality isn't ready yet. 

When it is, we should add publish those sections into the first-application page (getting-started/first-application/)

cc @rynowak @AaronCrawfis @jasonviviano 

[AB#5468](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5468)

**Comment by Reshrahim** [comment]
Recipes are added to run your first app under getting started. Closing this
