### ISSUE TITLE
Supported Kubernetes clusters

### ISSUE THREAD

**Issue by vmarchese** [radius-project/docs#455]
A note should be added to clarify the right minimum kubernetes version.
For instance, for kind,  the right `kindest/node` image 

[AB#5507](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5507)

**Comment by vmarchese** [comment]
Also, it is not clear if there is  support for ARM64 archs (i.e. Mac M1)

**Comment by AaronCrawfis** [comment]
Thanks for the feedback! I'll work on getting minimum Kubernetes versions added to https://docs.radapp.dev/operations/platforms/kubernetes/supported-clusters/ as soon as possible.

As for M1 Mac support, please try installing Rosetta from Terminal via:

```bash
softwareupdate -install-rosetta -agree-to-license
```

This should allow Docker Desktop to run x64 images within the Docker VM.

I've also opened https://github.com/project-radius/radius/issues/4937 to track native support.

**Comment by AaronCrawfis** [comment]
Added a section on minimum version here: https://github.com/project-radius/docs/commit/41a95a026ee4f84ab3bd437e7aa7d72455930ab3

Docs: https://docs.radapp.dev/operations/platforms/kubernetes/supported-clusters/
