### ISSUE TITLE
Initialize an environment: No bitnami/contour:7.4.6 helm chart in bitnami repo

### ISSUE THREAD

**Issue by vmarchese** [radius-project/docs#456]
# Context
1. macOS Monterey , v.12.5.1 on a MacBook Pro (Apple M1 Max)
2. Following the tutorial to setup a radius environment on an AKS cluster on an Azure subscription

# Expected Behaviour 
Pods up and running in the control plane namespace as per documentation 

# Current Behaviour 
The command `rad env init kubernetes -i` with the following configuration fails with the following error:

```
Error: failed to get contour chart, err: chart "contour" version "7.4.6" not found in https://charts.bitnami.com/bitnami repository, helm output:
```
No further output

The only pods running are the following:

```
> k get pods
NAME                          READY   STATUS    RESTARTS   AGE
appcore-rp-67474855bb-wlcnm   1/1     Running   0          12s
bicep-de-5fc5656bb5-dprx8     1/1     Running   0          11s
ucp-676bb77d98-x5hkk          1/1     Running   0          11s
```

# Steps to reproduce

1. Add the AKS credential to the kubectx configuration
2. Switch the kubectl context to AKS
3. Launch the command `rad  env init kubernetes -i`
4. Fill the questions with the following answers:
```
Enter a namespace name to deploy apps into: radius
Add Azure provider for cloud resources [y/N]?: N
Add AWS provider for cloud resources [y/N]?
Enter an environment name: aks-test-radius
Installing Radius version v0.16.0 control plane...
```

# Further Info
The installation seems to be in an inconsistent state (no `--atomic` option in `helm install`?):
1. `helm list` reports:
```
helm list
NAME  	NAMESPACE    	REVISION	UPDATED                             	STATUS  	CHART        	APP VERSION
radius	radius-system	2       	2022-12-27 10:09:40.890113 +0100 CET	deployed	radius-0.16.0
```

2. The `rad env list` command complains with `no resource group set, use '--group' to pass in a resource group name`
3. The `rad group  list` command fails with the following output
```
Error: GET https://........hcp.westeurope.azmk8s.io:443/apis/api.ucp.dev/v1alpha3/planes/radius/local/resourcegroups
--------------------------------------------------------------------------------
RESPONSE 503: 503 Service Unavailable
ERROR CODE UNAVAILABLE
--------------------------------------------------------------------------------
error trying to reach service: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "ucp-ca")

--------------------------------------------------------------------------------
```

[AB#5512](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5512)

**Comment by AaronCrawfis** [comment]
@vmarchese thank you for the feedback! We've addressed this as part of https://github.com/project-radius/radius/pull/4933 and have released a patch version. Please visit https://docs.radapp.dev/getting-started/install/ and try again.
