### ISSUE TITLE
Prometheus & Grafana setup

### ISSUE THREAD

**Issue by anamikapan** [radius-project/docs#457]
### Introduction 

In general, observability is the extent to which you can understand a complex system's internal state or condition based only on knowledge of its external outputs. The more observable a system, the more quickly and accurately you can navigate from an identified performance problem to its root cause, without additional testing or coding. 

While some data points about an application can be gathered from the underlying infrastructure (for example memory consumption, CPU usage), other meaningful information must be collected from an “application-aware” layer–one that can show how an important series of calls is executed across microservices. This usually means a developer must add some code to instrument an application for this purpose. Often, instrumentation code is simply meant to send collected data such as traces and metrics to observability tools or services that can help store, visualize and analyze all this information. 

 
### Observability versus monitoring 

Observability and monitoring are separate but supplemental concepts. A simple way to distinguish the two is that monitoring works by collecting and analyzing data known to be related to application, system or network performance issues, while observability gives teams the contextual information needed to identify and respond to “unknown unknowns,” or issues teams are not yet aware of. 

 
### Three pillars of observability  

Application observability focuses on four main telemetry types, the three pillars of observability — logs, metrics, and traces — and dependencies. 

**Logs-** Logs are granular, timestamped, complete and immutable records of application events that come in three formats: plain text, structured or binary. Among other things, logs can be used to create a high-fidelity, millisecond-by-millisecond record of every event, complete with surrounding context, that developers can “play back” for troubleshooting and debugging purposes. 

**Metrics-** Metrics (sometimes called time-series metrics) are fundamental measures of application and system health over a given period of time, such as how much memory or CPU capacity an application uses over a five-minute span, or how much latency an application experiences during a spike in usage. 

**Traces-** Traces record the end-to-end “journey” of every user request, from the UI or mobile app through the entire distributed architecture and back to the user. 

### General flow diagram for a deployed Kubernetes cluster 

 
<img width="839" alt="Screenshot 2022-12-27 at 11 11 42 AM" src="https://user-images.githubusercontent.com/110430621/209712142-d31bea55-1456-4e2f-b636-b0e4f497b391.png">

**TODO**: We can make sure to specify the radius control plane and make this flow specific for our use case 

### Steps to setup Prometheus & Grafana 

Helm helps you manage Kubernetes applications — Helm Charts help you define, install, and upgrade even the most complex Kubernetes application. 

**Steps :** 

Install Helm on your device- https://helm.sh/docs/intro/install/ 

Make sure your docker is running locally - https://phoenixnap.com/kb/docker-run-command-with-examples or you can make sure your docker desktop is running and it can spin a container directly using a run button on it. After the initial set up is done follow the steps below to install and run prometheus and grafana using helm 

- helm repo add prometheus-community  https://prometheus-community.github.io/helm-charts 
- helm repo add grafana  https://grafana.github.io/helm-charts 
- helm repo update 
- helm install prometheus prometheus-community/prometheus 
- helm install grafana grafana/grafana 

<img width="1240" alt="Screenshot 2022-12-27 at 11 13 04 AM" src="https://user-images.githubusercontent.com/110430621/209712456-675653ee-030e-4c16-9ee0-a194220e3e51.png">

- Make sure to access the password as specified using - 
kubectl get secret --namespace default grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo 

- Navigate to localhost:3000 in your browser. You should see a Grafana login page. 
Sign In using username admin and generated password 

You can specify the data source (in our case Prometheus) which can be conncected to our grafana dashboard and display the logs/metrics to the end user. 

The ip for prometheus endpoint can be found by using kubectl get pod -o wide 

<img width="999" alt="Screenshot 2022-12-27 at 11 13 37 AM" src="https://user-images.githubusercontent.com/110430621/209712544-872e8a4f-aad4-4d9a-92db-b0a952e46189.png">

[AB#5513](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5513)

**Comment by AaronCrawfis** [comment]
Docs are now in
