### ISSUE TITLE
Feature: Add a document that describes how to setup Radius on an on-prem kubernetes cluster  

### ISSUE THREAD

**Issue by asilverman** [radius-project/docs#460]
## Overview of feature request

Currently our documentation describes how we can run Radius on EKS/AKS and locally hosted kubernetes clusters. 

Some customers may deploy their production workloads on kubernetes clusters deployed in-premises (["the hard way"](https://github.com/kelseyhightower/kubernetes-the-hard-way)) and could benefit from a getting started document that describes how to spin up a Radius application running on this kind of deployment.

## Acceptance criteria

Add a section to the documentation that describes how to install Radius in a kubernetes cluster hosted in-prem (that is not locally hosted like kind/k3d and not managed by a cloud provider like aks/eks).

## Additional context

Having such a setup will also help us validate that we work well on this kind of deployment which operates differently in terms of the networking stack (CNI). 

I'm adding this feature request as a reminder to learn how to configure a Radius Gateway on this kind of deployment since I'm not privy to how this would actually work

[AB#5690](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5690)

[AB#5697](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5697)

**Comment by AaronCrawfis** [comment]
Docs here: https://docs.radapp.dev/operations/platforms/kubernetes/supported-clusters/

**Comment by asilverman** [comment]
I think that perhaps I didn't make the issue clear enough. The document referenced above is for kind, aks, eks and others. I am asking for a document that shows how to setup on a k8s cluster that is a production on-prem cluster. For example if you spin a VMSS cluster and installed k8s the hard way on them there is no clear guidance on how to setup radius there and also no guarantee that it would work because its not being tested at all by the team
