### ISSUE TITLE
[Run your first app] App browser image is different than actual app website

### ISSUE THREAD

**Issue by kachawla** [radius-project/docs#468]
App image listed in `4. Run the app` section under `Access the application by opening http://localhost:3000/ in a browser:` looks different than the actual app I see when I go to http://localhost:3000/

Here's what I see -

<img width="1119" alt="Screenshot 2023-02-02 at 6 31 21 PM" src="https://user-images.githubusercontent.com/74574173/216498525-3b0a7afb-287b-4700-b591-c2a8bdc56cfd.png">

here's what we have in docs -
https://github.com/project-radius/docs/blob/edge/docs/content/getting-started/first-app/demo-screenshot.png

[AB#6059](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/6059)

**Comment by AaronCrawfis** [comment]
This has been fixed, was using an old image. Please reopen if you hit this again
