### ISSUE TITLE
Add architecture docs on AWS support in Radius

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/docs#470]
a.	Credentials for AWS Cloud provider – What and How?
b.	AWS bicep extensibility
c.	UCP interaction with AWS resources

[AB#6063](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/6063)

**Comment by jonvsm** [comment]
@Reshrahim and @rynowak, is this content going to be part of RyanN's larger Concept: Architect doc or will it land somewhere else?

**Comment by rynowak** [comment]
@jonvsm - based on the description it sounds like `a` and `b` land somewhere else. `c` is already covered in the architecture doc.

**Comment by Reshrahim** [comment]
Aws architecture content is covered in the Architecture doc and  the other docs are covered in 

https://docs.radapp.dev/guides/author-apps/aws/
https://docs.radapp.dev/guides/operations/providers/howto-aws-provider/#manual-configuration
