### ISSUE TITLE
Add supported AWS services in Radius and workarounds 

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/docs#472]
1. List of AWS services that could be modeled in Bicep today 
2. Workarounds or non-bicep experience for not supported services

[AB#6066](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/6066)

**Comment by jasonviviano** [comment]
@Reshrahim Hey could you double check if this issue has been addressed, I saw there's 2 pages that might tackle this found here:

- https://edge.docs.radapp.dev/guides/author-apps/aws/howto-aws-resources/
- https://edge.docs.radapp.dev/guides/author-apps/aws/overview/
