### ISSUE TITLE
`rad init` missing from cli reference docs

### ISSUE THREAD

**Issue by kachawla** [radius-project/docs#479]
https://edge.docs.radapp.dev/reference/cli/

[AB#6087](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/6087)

**Comment by bjoginapally** [comment]
docs not being generated because of hidden command. fix: https://github.com/project-radius/radius/pull/5114

**Comment by AaronCrawfis** [comment]
Closing as `rad init` is now unhidden and in the docs
