### ISSUE TITLE
Automate documentation spellcheck and style guide 

### ISSUE THREAD

**Issue by asilverman** [radius-project/docs#483]
# Summary

Currently docs spelling and style conformance is manual, this issue proposes using automation to ease the burden on reviewers and maintain consistency.

## Impact

* Automating the spellcheck and style shortens the developer inner loop when working with documentation and reduces the burden on reviewers by enforcing consistently the style guidelines which helps reviewers focus their energy on the content semantics instead of nit-picks.
* Automation ensures documentation consistency (on the rules it enforces)

Of course, the automation should be calibrated and tuned to fit our needs.

## Proposal

* Review the linters below to determine how they align with the doc needs for Radius
  * [get-alex/alex: Catch insensitive, inconsiderate writing (github.com)](https://github.com/get-alex/alex)
  * [amperser/proselint: A linter for prose. (github.com)](https://github.com/amperser/proselint)
  * [textlint · The pluggable linting tool for text and markdown](https://textlint.github.io/)

* Configure the linter with relevant rules/exclusions and add a non-gating github action in the docs CI/CD execution to trial the functionality 
 

[AB#6131](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/6131)

**Comment by AaronCrawfis** [comment]
Spellcheck has been added: https://edge.docs.radapp.dev/community/contributing/docs/#spelling. No current plans for style linting until we have a more rigid set of requirements.
