### ISSUE TITLE
Cloud providers configuration page is too hard to find

### ISSUE THREAD

**Issue by rynowak** [radius-project/docs#490]
I spent 5 mins today looking for the Azure setup instructions...

I find it really hard to find this page, I would not have thought to look under "Control Plane". I ended up trying like 10 other topics first.

<img width="360" alt="image" src="https://user-images.githubusercontent.com/1430011/220730303-70a48745-a27d-4491-af51-06a8530980f0.png">

I think we could improve this by removing the term "control plane" from the docs, and replacing it with the word "Configuration" or the topic "Configuring Radius". I don't think most readers know what a control plane is or what topics belong to that category.

[AB#6258](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/6258)

**Comment by AaronCrawfis** [comment]
Moved: https://docs.radapp.dev/operations/providers/

**Comment by Reshrahim** [comment]
@AaronCrawfis - I don't see providers as a first-class section under administrator guides?

**Comment by AaronCrawfis** [comment]
> @AaronCrawfis - I don't see providers as a first-class section under administrator guides?

Fixed. We didn't do an upmerge to 0.19 yet. Got one in
