### ISSUE TITLE
Cloud providers instructions for Azure refer to `rad init kubernetes ...`

### ISSUE THREAD

**Issue by rynowak** [radius-project/docs#491]
These docs need to be updated for `rad init kubernetes`

https://docs.radapp.dev/operations/platforms/kubernetes/supported-clusters/#supported-clusters

[AB#6260](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/6260)

**Comment by AaronCrawfis** [comment]
Fixed as part of https://github.com/project-radius/docs/pull/512
