### ISSUE TITLE
Create a page on how Radius fits in brownfield scenario

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/docs#505]
We need to have a story for customers who already have their app deployments done via existing tool set and how Radius fits in and can provide value on the incremental adoption 

[AB#6533](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/6533)

**Comment by AaronCrawfis** [comment]
Closing as duplicate of #316
