### ISSUE TITLE
Document deletion behavior of recipes

### ISSUE THREAD

**Issue by rynowak** [radius-project/docs#520]
We're missing docs covering the deletion behavior of a recipe. We should cover the following:

- Resources created in Bicep will be deleted by Radius as part of the recipe's lifecycle
- Resources returned as part of `result.resources` will be deleted by Radius as part of the recipe's lifecycle
- Resources that are referenced as `existing` and not returned as part of `result.resources` will not be deleted by Radius

[AB#7196](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7196)

**Comment by shalabhms** [comment]
@rynowak , please confirm if this is not covered in the doc #517.

**Comment by jasonviviano** [comment]
@rynowak Hey just wanted to do another follow up and understand if the current [Recipe overview](https://edge.docs.radapp.dev/guides/recipes/overview/#infrastructure-lifecycle) page covers or gives users the right context for the deletion.

**Comment by rynowak** [comment]
I think we can close this, this is done.
