### ISSUE TITLE
On edge some images are using latest instead of edge

### ISSUE THREAD

**Issue by ytimocin** [radius-project/docs#522]
Example:

![image](https://user-images.githubusercontent.com/5220939/228957020-1b6da9b8-6f14-4ec2-adac-580771eb1f22.png)

I will add here if I find more...

[AB#7211](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7211)

**Comment by shalabhms** [comment]
@AaronCrawfis , could you please update what could be the action item here? Should we continue start using 'latest'  instead of 'edge'?

**Comment by AaronCrawfis** [comment]
> @AaronCrawfis , could you please update what could be the action item here? Should we continue start using 'latest' instead of 'edge'?

For consistency let's use `edge`. Let's keep this item open to track making sure we're consistent.

**Comment by jasonviviano** [comment]
@AaronCrawfis Hey is this still a relevant issue? There's another issue opened up about moving away from `edge`, https://github.com/radius-project/docs/issues/632

**Comment by AaronCrawfis** [comment]
Closing as we'll tackle this in #632
