### ISSUE TITLE
Azure Storage State Store Bicep File points to the latest image which doesn't exist

### ISSUE THREAD

**Issue by ytimocin** [radius-project/docs#523]
![image](https://user-images.githubusercontent.com/5220939/228958336-6c409a70-dddb-4eaa-afd3-2208e7463dd3.png)

It makes the container fail.

[AB#7212](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7212)

**Comment by shalabhms** [comment]
Depends on the closure of this https://github.com/project-radius/docs/issues/522

**Comment by AaronCrawfis** [comment]
This has been addressed as part of Dapr tutorial revamp: https://edge.docs.radapp.dev/tutorials/dapr/
