### ISSUE TITLE
The connections part in the Dapr bicep files may need an update

### ISSUE THREAD

**Issue by ytimocin** [radius-project/docs#524]
![image](https://user-images.githubusercontent.com/5220939/228961388-22951f2a-5509-4270-82d1-1c7c7c35c246.png)

1. I download and deploy these two bicep files.
2. I run the tunnel expose: `rad resource expose containers backend --application dapr-quickstart --port 3000`
3. I go to `http://localhost:3000/order`
4. I see: `{"message":"The container is running, but the state store name is not set."}`

[AB#7213](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7213)

**Comment by willtsai** [comment]
this will be addressed by https://github.com/project-radius/docs/pull/636

**Comment by willtsai** [comment]
resolved by https://github.com/project-radius/docs/pull/636
