### ISSUE TITLE
Documentation for k8s incremental adoption and migration guidance

### ISSUE THREAD

**Issue by willtsai** [radius-project/docs#526]
once the work in https://github.com/project-radius/radius/issues/5121 and https://github.com/project-radius/radius/issues/5122 is done, we need to publish some guidelines on _how_ users can go about migrating their k8s apps to Radius and incrementally adoption Radius features that are not available in k8s.

# Concepts and Migrations 

We provide documentation on the conceptual mapping between Radius' concepts and Kubernetes concepts [here](https://docs.radapp.dev/operations/platforms/kubernetes/resource-mapping/). 

This section will go beyond the basics and also discuss techniques for migration. 

## Applications 

The application maps to a Kubernetes namespace. The namespace names we use by default are a combination of the environment name and application name. Users can [choose](https://docs.radapp.dev/operations/platforms/kubernetes/resource-mapping/#namespace-mapping) a free-form name when creating the application resource, which can be used to preserve their existing namespace. 

While Kubernetes does not have a concept of application, users can think of everything in a namespace as "the application" without issue. Radius will validate the name and prevent collisions between applications that attempt to share a namespace name. 

### Guidance:  

If other applications in the same cluster or existing tools already have knowledge of the current namespace, then configure the application resource to match the currently used namespace. 

If the above is false, then choose a meaningful application name and Radius will manage the namespace.  

## Containers 

Containers are the standard unit of compute, and map to some combination of the following primitives in Kubernetes in common usage. For example, a Helm chart that deploys a single microservice will likely contain: 

- Deployment (exactly 1) 
- Service (0-1) 
- ServiceAccount (0-1) 
- Secret/ConfigMap (0-many) 

We would recommend that every chart/microservice map to a single Radius container. The assets listed above are the same as the assets we create in Radius based on your container definition. 

### Guidance: 

For each microservice ... 

- Check the names of your Kubernetes resources and align them on a single name. If your container is going to be called store then call all of the resources in your chart store as well. 
- If you have a helm chart, then run helm template to extract the raw YAML and save it on disk in your repo. 
- Create a Radius container definition 
  - Set .properties.container.image to none 
  - Set .properties.runtimes.kubernetes.base to point to your raw YAML. 
- Deploy 
  - Radius will "take ownership" of the Kubernetes resources already there and update them. 
  - You should have a working microservice that was deployed by Radius, with no change in behavior. 
- You're now ready to start adopting Radius features like recipes, connections, and the application graph. 

Once you get everything working you could decide to remove your Kubernetes assets in favor of Radius' definitions. There's likely a lot of duplication between what you wrote out and what Radius will generate by default. 

Each of these steps can be done separately to ensure the app keeps working. 

For each microservice... 
- Add .properties.container.ports to the Radius container, and remove your Kubernetes Service. 
- Add container primitives (env vars, command line args, health checks, volumes) to the Radius container and remove these from your deployment. 
- At this point is there anything left? If not, you're done, delete the chart. 
- If you have anything left, then you can use the “patch” feature to access Kubernetes-specific settings or idioms. 
  - Add .properties.runtimes.kubernetes.patch 
  - Copy all of the remaining fields on the Deployment's .spec.template.spec into the patch. 
  - If you have Secrets or ConfigMaps then you can either keep them around as a "base" or use Bicep Kubernetes support to manage them. 
  - Now you're done! 

If we desire in the future, these steps could be automated after these features have been built. For example, it’s easy for us to scan a repo and report on Kubernetes YAML or charts that we find. It’s easy for us to do analysis on Kubernetes definitions and recommend the exact strategy or generate output.

[AB#7254](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7254)

**Comment by jasonviviano** [comment]
@willtsai Hey is this related to this PR: https://github.com/radius-project/docs/pull/748 also have a PR almost out on the pod method incremental steps.
