### ISSUE TITLE
Concepts and getting started sub menu links

### ISSUE THREAD

**Issue by cachaldora** [radius-project/docs#530]
In concepts documentation page you can see a sub menu with links to other related sub pages and there are two issues:

- Inside each page you have next step on bottom but it doesn't seem to follow the same order in which pages are listed in sub menu. Example: when you are at [app model page](https://docs.radapp.dev/concepts/appmodel-concept/) you have as next step [links page](https://docs.radapp.dev/concepts/links-concept/) but in concepts sub menu the page above is [environments](https://docs.radapp.dev/concepts/environments-concept/);
- Still in concepts sub menu the order of each page doesn't seems to make sense, I'm expecting to find architecture page before environments and links pages;

These two issues also happens in getting started sub menu and pages.

[AB#7297](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7297)

**Comment by jasonviviano** [comment]
Hey @cachaldora! I would love to also understand if you've found the actual Concepts Page menu order easy to digest or if you had any other feedback regarding that flow?

**Comment by AaronCrawfis** [comment]
Closed by https://github.com/project-radius/docs/pull/539
