### ISSUE TITLE
Suggestion for alternative directory install doc

### ISSUE THREAD

**Issue by cachaldora** [radius-project/docs#531]
When installing rad cli you mention how to install it in another directory using RADIUS_INSTALL_DIR.
A good nice to have also on that note would be how to add the directory or binary to the user path.

Add a link to some guide on internet is also a nice option.

[AB#7298](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7298)

**Comment by AaronCrawfis** [comment]
Added this in 0.20, thanks for the suggestions!
