### ISSUE TITLE
Radius concepts grammar standardization

### ISSUE THREAD

**Issue by jasonviviano** [radius-project/docs#540]
## Description

Let's standardize if Radius Recipe or Radius recipe or Radius application or Radius Application is the correct way in the docs and add it to the contribution page.

[AB#7507](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7507)

**Comment by shalabhms** [comment]
It looks like this is closed as part of the https://github.com/project-radius/docs/pull/542 .  @jasonviviano , please reopen if there is anything pending here.

**Comment by shalabhms** [comment]
It looks like this is closed as part of the https://github.com/project-radius/docs/pull/542 .  @jasonviviano , please reopen if there is anything pending here.
