### ISSUE TITLE
Failed to load https://edge.docs.radapp.dev/swagger/specification/ucp/resource-manager/UCP/preview/2022-09-01-privatepreview/ucp.json: 404 Not Found

### ISSUE THREAD

**Issue by jasonviviano** [radius-project/docs#547]
## Description

UCP API is not loading on both `edge` and `stable` version of the Radius docs

## Image
<img width="1329" alt="Screenshot 2023-04-24 at 4 51 25 PM" src="https://user-images.githubusercontent.com/83607984/234114395-979564c8-78eb-4ed7-9380-4cb49bdf5ef2.png">

[AB#7654](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7654)

**Comment by AaronCrawfis** [comment]
Closed by https://github.com/project-radius/docs/pull/548
