### ISSUE TITLE
Updating pages to follow casing convention

### ISSUE THREAD

**Issue by jasonviviano** [radius-project/docs#550]
## Description
Find pages that reference Radius Application, Radius Environment, etc.. that don't follow the casing convention in the contribution page.

[AB#7705](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7705)

**Comment by AaronCrawfis** [comment]
Casing decisions:

- "Radius Recipes"
- "Radius Applications"
- "Radius Environments"
- "Radius Connections"
- "local-dev Recipes"
- "Radius resources"
- "Radius control plane"
- "Radius portable resources"
