### ISSUE TITLE
Add "let us know" links to Sample documentation

### ISSUE THREAD

**Issue by sylvainsf** [radius-project/docs#563]
As we are implementing minimal automated sample testing a good catchall would be to add "Radius is has a rapid development pace, if you encounter any issues in using this sample please let us [know!](https://github.com/project-radius/docs/issues/new/choose)

[AB#7870](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7870)

**Comment by AaronCrawfis** [comment]
Added a place to open an issue, which is visible on every page: 
<img width="232" alt="image" src="https://github.com/project-radius/docs/assets/54363786/61bab1c7-edc2-43ba-943b-90382dabc7ad">

This will lead users to a page where they can file a bug/request:
https://github.com/project-radius/radius/issues/new/choose

<img width="1094" alt="image" src="https://github.com/project-radius/docs/assets/54363786/89607a04-ab12-4fd7-85b7-ded0aa3e73b5">
