### ISSUE TITLE
API version to use is not obvious in Radius API docs 

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/docs#565]
Partner team is trying to use radius API's to visualize the application graph. Hard to find  the api version from our docs. We should call this out explicitly somehow

https://docs.radapp.dev/reference/api/applications.core/applications/

[AB#7873](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7873)

**Comment by jasonviviano** [comment]
Closing, we now have a guide on how users can interact with the Radius API through postman and the version to use:

https://edge.docs.radapp.dev/guides/operations/control-plane/howto-postman/
