### ISSUE TITLE
Show examples of root scope (path parameters) for Radius api's in docs

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/docs#572]
Partner team was stuck on what to add as the root scope path parameter. Would be good to show examples

https://docs.radapp.dev/reference/api/applications.core/applications/#tag/Applications/operation/Applications_ListByScope

[AB#7913](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7913)

**Comment by AaronCrawfis** [comment]
This has been addressed as part of https://edge.docs.radapp.dev/guides/operations/control-plane/howto-postman/
