### ISSUE TITLE
Add more clear instructions on first-app page

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/docs#586]
This is a compiled list of feedback from a user who recently tried the first app experience

Add clear instructions on 
 -  Install recommended bicep popup 
    -  User explicitly asked what needs to be done  
 -  Where to place the DB connection block?
     - User feedback: got a little bit confused on the DB connection block as to where exactly I was supposed to put this. Umm had I looked ahead to the full file right here I I would have figured that out.
 - Codespace instructions on which step to start and not navigate to localhost:3000 after deploying app
 -  In step 4, make instructions clear to say run `rad run app. bicep`
      - User ran just rad run following just instructions without looking at the command below
 -  In the final step, highlight the todo app via a screenshot
     - The user was confused about where the to-do list menu is 

    

[AB#7952](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7952)

**Comment by willtsai** [comment]
Adding one more issue to this list - in several places code blocks break up the content, causing the user to jump ahead into trying to figure out where to paste the code block rather than reading further to get the instructions. Will add to the above PR to correct this.

**Comment by AaronCrawfis** [comment]
Closed as part of #680 and updates to the Todo app container homepage

**Comment by Reshrahim** [comment]
This is not closed yet. Feedback about the codespace and VSCode extension (recommendation popup) is not addressed yet. Tracking to complete those after open-sourcing

**Comment by jasonviviano** [comment]
Closing, there's an ADO issue tracking the VSCode extension work and codespace work is out-of-scope for public-release
