### ISSUE TITLE
Update Dapr quickstart to follow new format

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/docs#592]
## Current state

The Dapr quickstart is currently a multi-page guide that follows our old tutorial format: https://docs.radapp.dev/getting-started/quickstarts/quickstart-dapr/

## Desired state

The Dapr quickstart is a one-page quickstart that more concisely introduces Dapr and its value-props.

[AB#8034](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/8034)

**Comment by willtsai** [comment]
resolved by https://github.com/project-radius/docs/pull/636
