### ISSUE TITLE
Dapr tutorial bicep files fail to download

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/docs#63]

**Comment by jkotalik** [comment]
Seeing this too, looks like the download ends up leading to a csv file.

**Comment by nithyatsu** [comment]
https://radapp.dev/user-guides/tutorials/dapr-microservices/add-dapr/ has links that lets me download, but links on https://radapp.dev/user-guides/tutorials/dapr-microservices/add-frontend/ dont work. 
And in the downloads there is no connector that the tutorial talks about :  
missing connections: {
        statestore: {
          kind: 'dapr.io/StateStore'
          source: daprBackend.id
        }

     }

But even after adding the connections I dont get the env variable that the tutorial mentions at "Radius will inject information related to the state store using the environment variable CONNECTION_STATESTORE_ORDERS"

**Comment by AaronCrawfis** [comment]
Root cause was https://github.com/project-radius/docs/blob/edge/docs/config.toml#L9

**Comment by nithyatsu** [comment]
@ytimocin  filed this as well https://github.com/project-radius/docs/issues/72. The links should have the full content ...
