### ISSUE TITLE
Getting started page is challenging

### ISSUE THREAD

**Issue by ryanwaite** [radius-project/docs#637]
Several issues with the page:

Why is "Run Your First App" above "Install Radius"? Isn't it reasonable to assume we've need to Install Radius to Run Your First App? Acorn.io has a nice Getting Started from their page that just goes to the https://docs.acorn.io/ which is lovely, explaining the product, the prerequesites and steps to get started. Same with Promethius.io. You go to a substantial page with the information you need. 

Why is there so little information about each of these options? 

Why is Concepts above Getting Started in the TOC? It makes me think I should go to Concepts and then go to Getting Started

[AB#8608](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/8608)

**Comment by ryanwaite** [comment]
Also, why are there so many Tags to the Getting Started page? For example, why is there a Dapr tag to the Getting Started page? Or a Secrets tag?

**Comment by AaronCrawfis** [comment]
> Also, why are there so many Tags to the Getting Started page? For example, why is there a Dapr tag to the Getting Started page? Or a Secrets tag?

The Docsy theme shows you all the tags and categories within all of the docs, not just in the current page/section. Agree that it can be improved. cc/ @Reshrahim
