### ISSUE TITLE
Verify and document the deletion behavior for a Radius application

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/docs#654]
This came in as feedback from the sprint 1 review. 

1. Understand if Radius-created resources are deleted when an application is deleted 
2. What is the behavior for resources that existed already 

[AB#8782](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/8782)

**Comment by willtsai** [comment]
documentation does look rather sparse on this topic: https://docs.radapp.dev/reference/cli/rad_application_delete/
