### ISSUE TITLE
Ensure docs reflect that there is no support for windows as a dev-environment

### ISSUE THREAD

**Issue by asilverman** [radius-project/docs#66]
**Observed behavior**
As discussed in [conversation_wsl.pdf](https://github.com/project-radius/radius/files/8399931/convo_wsl.pdf), we are not supporting wsl as a dev environment, we should update the docs accordingly [here](https://radapp.dev/contributing/contributing-code/contributing-code-first-commit/first-commit-00-prerequisites/)

**Comment by AaronCrawfis** [comment]
The contributing docs were moved to the radius repo as part of https://github.com/project-radius/radius/pull/1972

Aman is adding WSL clarification as part of https://github.com/project-radius/radius/pull/2154

**Comment by amanbha** [comment]
closed in https://github.com/project-radius/radius/pull/2154
