### ISSUE TITLE
VS Code is not the path by default on MacOS 

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/docs#664]
## Summary
Captured as part of a usability study with first-app experience

Our installation instructions assume VS Code is on the path, it is not set up this way by default on Mac. 
We should link to the VS Code documentation for this. 

[AB#8878](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/8878)

**Comment by willtsai** [comment]
this is already addressed and documented in https://docs.radapp.dev/getting-started/install/
