### ISSUE TITLE
Provide more context when customer gets to "Welcome to Radius Demo" page

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/docs#665]
## Summary

Captured as part of a usability study with first-app experience

User did not understand the "Welcome to Radius Demo" page… He said, "I don't know what I'm looking at but I'm looking at something." Explain more clearly what the I am seeing and what steps to take

[AB#8882](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/8882)

**Comment by willtsai** [comment]
Other feedback I've observed from users is to bring the TODO app to a more prominent space in the web app

**Comment by AaronCrawfis** [comment]
This has been fixed. Demo container has a refreshed design.

**Comment by Reshrahim** [comment]
@AaronCrawfis - should we update the images in the first-app doc if the demo container is refreshed

**Comment by AaronCrawfis** [comment]
> @AaronCrawfis - should we update the images in the first-app doc if the demo container is refreshed

Good catch: https://github.com/radius-project/docs/pull/779
