### ISSUE TITLE
First App Experience doc:  shorten Recipes content

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/docs#666]
## Summary

Captured as part of a usability study with first-app experience

The user followed the link to the Recipes information and started reading it.  He said "Alright, I'm bored."  implying there was too much text to wade through on that page.

## Proposed action: 
Do a close edit of the content for brevity and clarity

[AB#8883](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/8883)

**Comment by willtsai** [comment]
More notes from triage: The spirit of the feedback was that the information presented on [that page](https://docs.radapp.dev/author-apps/recipes/) wasn't what the user was hoping to see. They were hoping to see a page that explains all the developer info relating to connections and env vars.

Quick fix might be to remove the link to this page given that it's not helpful. Will also revamp docs to have more detailed how-to guides for developers.

**Comment by AaronCrawfis** [comment]
Closing as there's already a clear progression through the first app experience. There's value in having cross-links that can optionally be followed, and it's up to the user to follow the guide and optionally follow the links.
