### ISSUE TITLE
First App Experience doc: Be explicit about which "properties" to edit

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/docs#667]
## Summary
Captured as part of a usability study with first-app experience

When adding a Redis cache, there are two "properties": one in the app block and one in the Redis cache block

## Proposed action
Make the docs explicit that the customer needs to edit the property in the Redis cache block

[AB#8884](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/8884)

**Comment by willtsai** [comment]
This feedback is common, best solution would probably be some sort of mechanism to highlight diffs in the code blocks to show users exactly where to add the code.

**Comment by Reshrahim** [comment]
completed by https://github.com/project-radius/docs/pull/684
