### ISSUE TITLE
First app experience docs: Change environment name to something other than 'default'

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/docs#669]
## Summary
Captured as part of a usability study with first-app experience

In the first app experience, name the environment something other than "default"
It's confusing for someone who has a Kubernetes namespace named "default" to also have a Radius environment named "default"

[AB#8888](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/8888)

**Comment by nicolejms** [comment]
Confusion around line between kubernetes namespace and environment and app.  should not change it.
