### ISSUE TITLE
First app experience tutorial diagram

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/docs#671]
## Summary
Captured as part of a usability study with first-app experience

Tutorial content should include a diagram of the application to help users understand what’s happening. Include details like the connections and environment variables being used. This helps ground a developer in the details of what’s happening.

[AB#8893](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/8893)

**Comment by nicolejms** [comment]
not blocking public release so keeping in backlog
