### ISSUE TITLE
“Developing Applications” docs have too little content / information

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/docs#672]
## Summary
For example "Radius Application" page doesn't tell me anything. It looks more like a "To Do"
It's just kind of a glossary.  It at the least it needs graphics to provide some information
There is are so many titles to so little text… it's obvious there is very little info here
Lots of repeated words extension, extension, extension

## Proposed action
Shift this section to be focused on how a customer can use Radius to develop their own applications, use existing resources in a radius application, etc.  Make it clear in this section how I will use radius, point to examples of Radius applications that make it easier for me to understand how much of my code will be impacted by using Radius, how to radify a brownfield app, etc etc.
Add diagram and context and pointer to sample apps that help me understand what I am taking on by adopting Radius

[AB#8894](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/8894)

**Comment by nicolejms** [comment]
Aaron's work will solve this

**Comment by AaronCrawfis** [comment]
The Applications page has been refreshed with more information: https://edge.docs.radapp.dev/guides/author-apps/application/overview/
