### ISSUE TITLE
Overview Cloud providers doc: Clarify cloud provider vs platform

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/docs#673]
## Summary
Captured as part of a usability study with first-app experience
User could not figure out what these terms mean and how they are different

## Proposed action
Decide if these are the right terms and clarify their meaning

[AB#8896](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/8896)

**Comment by AaronCrawfis** [comment]
This has been addressed, `platforms` now doesn't appear in the docs: 
<img width="261" alt="image" src="https://github.com/project-radius/docs/assets/54363786/0ee2ccd3-6549-40e4-ba96-d2d2f91cf89a">
