### ISSUE TITLE
Tutorial: Add Radius to an existing application

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/docs#674]
## Summary
Captured as part of a usability study with first-app experience

It's unclear how much work is going to be required for me in my code. I need to see examples that give me a clearer indication of how. “I want to see how I write code that works with Radius. Give me some examples”.

## Proposed action:
Add a diagram, context, and pointer to an example code file that illustrates what it will take for me to use this
The "Developing Applications" section should address this
How do I use Radius in my app
How do I connect to existing resources I am using
Etc
Linking to a sample radius app in GitHub would also be valuable

[AB#8897](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/8897)

**Comment by Reshrahim** [comment]
@AaronCrawfis - Will this be tackled by #703 ?

**Comment by AaronCrawfis** [comment]
> @AaronCrawfis - Will this be tackled by #703 ?

Yep, will consolidate the issues. Thanks!

**Comment by willtsai** [comment]
closed - https://github.com/radius-project/docs/pull/870 and https://github.com/radius-project/samples/pull/626
