### ISSUE TITLE
Jaeger.yaml download is broken

### ISSUE THREAD

**Issue by rynowak** [radius-project/docs#675]
## Describe the bug

This link is broken: 

<img width="575" alt="image" src="https://github.com/project-radius/docs/assets/1430011/bf95e278-ebbd-4c41-b947-50a0c603b27d">

https://edge.docs.radapp.dev/operations/control-plane/observability/tracing/jaeger/

## Steps to reproduce

Click the link

## Expected behavior

Download works

[AB#8907](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/8907)

**Comment by AaronCrawfis** [comment]
Fixed. The App Service config didn't have the entry for YAML files, just JSON and Bicep.

File can now be downloaded on the main site and the edge site will be picked up on the next upmerge
