### ISSUE TITLE
Docs should state local and kubernetes env can't use Azure Cosmos DB

### ISSUE THREAD

**Issue by ytimocin** [radius-project/docs#70]
**Observed behavior**
Deploying the web app with Azure Cosmos DB in to a Kubernetes env hangs and will not succeed.

**Desired behavior**
Docs should be updated stating for each example of Azure Cosmos DB Kubernetes and local envs will not work.
`rad deploy` can also throw an exception based on the env and the resource type.

**OS/rad version**
edge      1c12fcd   0.4.1159  1c12fcd193607ec6afb759e5312a8801b066671f

**Comment by AaronCrawfis** [comment]
No longer applicable with the addition of Azure cloud providers
