### ISSUE TITLE
Concept: Portability

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/docs#708]
[AB#9071](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9071)

**Comment by ryanwaite** [comment]
@jonvsm can you look at the new Concept on Multi-Cloud and Open-Source and decide if we still want this concept doc on Portability?

**Comment by jasonviviano** [comment]
@jonvsm Is this addressed by the Multi-Cloud and Open-Source concept page?

Webpage: https://edge.docs.radapp.io/concepts/multi-cloud-concept/

**Comment by jonvsm** [comment]
Yes. What we were calling 'Portability' is covered in the "Multi-Cloud and Open-Source" concept page
