### ISSUE TITLE
Applications.Core API reference pages broken after move to TypeSpec

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/docs#730]
[AB#9202](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9202)

**Comment by jasonviviano** [comment]
Closing as it seems to be fixed, checked all the applications.core api pages on edge: https://edge.docs.radapp.dev/reference/api/applications.core/applications/
