### ISSUE TITLE
Tutorial: Make your application portable with Radius recipes

### ISSUE THREAD

**Issue by jasonviviano** [radius-project/docs#738]
[AB#9281](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9281)

**Comment by shalabhms** [comment]
@jasonviviano , could you please add more information in the issue?

**Comment by Reshrahim** [comment]
@AaronCrawfis / @jasonviviano - We do have a tutorial for [Recipes](https://edge.radapp.dev/tutorials/recipes/). Do we need to add or refine anything here?

**Comment by Reshrahim** [comment]
Closing as [recipes](https://edge.radapp.dev/tutorials/recipes/) tutorial already exists. Please reopen with more context if there are changes to be made.
