### ISSUE TITLE
Docs: Review usage of a `Blazor` front end component in the "Dapr microservices tutorial app overview" 

### ISSUE THREAD

**Issue by asilverman** [radius-project/docs#8]
Generally speaking, as a newbie that is struggling to learn a new concept and wants to quickly get "up and running" it is easier to use familiar things as examples to help build knowledge on the "new subject".

The "Dapr microservices tutorial" has many barriers towards this goal, the concept that I am looking to learn is "Radius & Dapr" however here since `.NET Blazor` is not a very popular and commonplace framework, I am forced to understand if its use is necessary or accidental in my ability to use "Radius & Dapr".

I think the tutorial needs to clarify this and also consider using a different more popular `frontend` framework that more potential customers will be familiarized with so that we offer relevant starter projects these potential customers can associate with their own when they explore using Radius & Dapr

Page Reference: https://edge.radapp.dev/user-guides/tutorials/dapr-microservices/overview/

**Comment by AaronCrawfis** [comment]
Thanks for the feedback! We've updated the tutorial to reflect that the user does not need to know Blazor, it's provided to them as a frontend UI
