### ISSUE TITLE
Codespaces should be default path for "Getting Started with Radius"

### ISSUE THREAD

**Issue by jonvsm** [radius-project/docs#813]
## What content needs to be created or modified?
I should not have to install a Kubernetes cluster to get through "Getting started with Radius."

## Describe the solution you'd like
A link to starting Codespace to complete this tutorial

## Where should the new material be placed?
Right after "Have your Kubernetes cluster handy"

## Additional context

[AB#9643](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9643)

**Comment by jonvsm** [comment]
I don't even see Codespaces as an option in the current doc version. Ideally, it would not only be an option but would be the default experience

**Comment by AaronCrawfis** [comment]
This will be added as soon as we go public to make sure people can access. We definitely want this to be the primary experience

**Comment by AaronCrawfis** [comment]
This has been completed. A note to use a Free codespace is now front and center in the getting started guide and is featured in the installation page.
