### ISSUE TITLE
Howto requires Helm to be installed but there are no previous docs which instruct the user to install Helm.

### ISSUE THREAD

**Issue by sylvainsf** [radius-project/docs#852]
Any howto should link to a "Install Helm howto" which doesn't exist yet so it's reusable. 

[AB#9733](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9733)

**Comment by AaronCrawfis** [comment]
Added in pre-reqs to jaeger/prometheus/grafana docs
