### ISSUE TITLE
Add a disclaimer note to readers that current How-Tos for Grafana and Prometheus 

### ISSUE THREAD

**Issue by jasonviviano** [radius-project/docs#860]
## What content needs to be created or modified?
Grafana and Prometheus how-to needs a warning note.

## Describe the solution you'd like
Add note to both pages

[AB#9830](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9830)

**Comment by nicolejms** [comment]
not a warning, just a disclaimer :)

**Comment by jasonviviano** [comment]
Closing as no longer the solution wanted instead will be using #918
