### ISSUE TITLE
Update code samples to point to ghcr 

### ISSUE THREAD

**Issue by jkotalik** [radius-project/docs#881]
**URL of the docs page**

https://docs.radapp.io/tutorials/new-app/#step-3-inspect-and-deploy-appbicep

Update `radius.azurecr.io/` to `ghcr.io/radius-project/`

**Screenshots**

![image](https://github.com/radius-project/docs/assets/8302101/c0f8157b-e4d0-4d66-ab72-28ff1c94897c)

**Additional context**

[AB#9855](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9855)

**Comment by jasonviviano** [comment]
Closing, fixed with: #889
