### ISSUE TITLE
Gettings started page does not load the image depicting the diagram of application and its resources

### ISSUE THREAD

**Issue by shivkanwer** [radius-project/docs#882]
## Describe the bug

Getting started page does not load the diagram image.

## Steps to reproduce

1. Navigate to the Getting started page - https://docs.radapp.io/getting-started

## Expected behavior

The architecture/application diagram image should load correctly.

## Screenshots

![image](https://github.com/radius-project/docs/assets/16209975/8e409951-1ae9-4c80-b0da-8a52c712ad40)

[AB#9857](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9857)

**Comment by zioproto** [comment]
It renders correctly on the GitHub preview here:
https://github.com/radius-project/docs/blob/v0.26/docs/content/getting-started/index.md

![Screenshot 2023-10-19 at 11 10 06](https://github.com/radius-project/docs/assets/789701/1e0652cf-5856-4e40-af2b-c616f9fb4741)

**Comment by shivkanwer** [comment]
I have observed that the images on the page don't render when navigating to https://docs.radapp.io/getting-started, however, if navigating to https://docs.radapp.io/getting-started/ the image load correctly. **The difference is '/' at the end of second URL**. 

When clicking on the _'Get Started'_ button on the home page (https://radapp.io/), the website navigates to https://docs.radapp.io/getting-started without a '/' in the end.

**Comment by willtsai** [comment]
This will actually get fixed by https://github.com/radius-project/docs/pull/886
