### ISSUE TITLE
Can't pull example image ghcr.io/radius-project/tutorial/webapp:edge

### ISSUE THREAD

**Issue by zioproto** [radius-project/docs#883]
## Describe the bug
Following the [Get Started](https://docs.radapp.io/getting-started)

the following `app.bicep` is created:

```
import radius as radius
param application string

resource demo 'Applications.Core/containers@2023-10-01-preview' = {
  name: 'demo'
  properties: {
    application: application
    container: {
      image: 'ghcr.io/radius-project/tutorial/webapp:edge'
      ports: {
        web: {
          containerPort: 3000
        }
      }
    }
  }
}
```

But I can't download the Docker image:

```
docker pull ghcr.io/radius-project/tutorial/webapp:edge
Error response from daemon: Head "https://ghcr.io/v2/radius-project/tutorial/webapp/manifests/edge": denied
```

## Steps to reproduce

```
docker pull ghcr.io/radius-project/tutorial/webapp:edge
Error response from daemon: Head "https://ghcr.io/v2/radius-project/tutorial/webapp/manifests/edge": denied
```

## Expected behavior
The image should be available for download

[AB#9859](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9859)

**Comment by zioproto** [comment]
I can instead pull the image `radius.azurecr.io/tutorial/webapp:edge` correctly.

Related to issue #881

**Comment by sylvainsf** [comment]
Fixed by [6520](https://github.com/radius-project/radius/pull/6520)
