### ISSUE TITLE
Diagram of the application and its resources is missing on the getting started page

### ISSUE THREAD

**Issue by abtin** [radius-project/docs#885]
## Describe the bug
On the [getting started](https://docs.radapp.io/getting-started) page, the _Diagram of the application and its resources_ isn't showing up.

## Steps to reproduce
Navigate to https://docs.radapp.io/getting-started and look for the first diagram.

## Expected behavior
A diagram of application and its resources to show up on the page.

## Screenshots
<img width="1411" alt="Radius_getting_started_missing_diagram" src="https://github.com/radius-project/docs/assets/441372/f58e5314-5697-4b09-8102-edda079ddaa0">

### Desktop (please complete the following information):

 - OS: MacOS (Not sure if it matters though)
 - Browser: Brave (Chromium)
 - Version: [Version 1.59.117 Chromium: 118.0.5993.70 (Official Build) (arm64)](https://brave.com/latest/)

## Additional context
Here is the HTML code of the element:
`<img src="diagram.png" alt="Diagram of the application and its resources" width="500px">`

[AB#9861](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9861)

**Comment by Reshrahim** [comment]
closed by #886

**Comment by abtin** [comment]
Thanks for the fix!
