### ISSUE TITLE
Docs website returns HSTS error

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/docs#894]
## Describe the bug

https://x.com/alkreddy/status/1714847929121312783?s=20

![image](https://github.com/radius-project/docs/assets/54363786/c9de0d6f-c905-4cf2-9de9-208f3851a72b)

## Steps to reproduce

1. Visit https://docs.radapp.io/getting-started

## Expected behavior

Expect to view website

### Desktop (please complete the following information):

 - OS: 
 - Browser 
 - Version 

### Smartphone (please complete the following information):

 - Device: 
 - OS: 
 - Browser 
 - Version 

## Additional context

[AB#9867](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9867)

**Comment by AaronCrawfis** [comment]
Unable to repro both on my machine (Windows 11 desktop) and on a fresh Windows VM in Azure. I tried setting strict mode, forcing various HTTPS-only modes and proxy modes and unable to get it to show the error.

If someone hits this again could they drop in their system specs and some information on their proxy setup? Reading through this post it seems like the proxy might be a possible issue: https://support.mozilla.org/en-US/questions/1324365

**Comment by alkreddy** [comment]
I confirm that it works fine now in my env. too. 
Not sure what caused the intermittent issue. 
You may close this issue.
