### ISSUE TITLE
Investigate why Grafana and Prometheus How-Tos appear to have issues for non-local usage

### ISSUE THREAD

**Issue by jasonviviano** [radius-project/docs#918]
## What content needs to be created or modified?
Prometheus and Grafana How-To guides.

## Describe the solution you'd like
Investigate more clearly what the environment issues are.

[AB#9977](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9977)

**Comment by shalabhms** [comment]
triage: To test out the Grafana/Promotheus how-tos in Azure environment instead of local environment.

**Comment by AaronCrawfis** [comment]
Works fine for me on AKS:
![image](https://github.com/radius-project/docs/assets/54363786/b9e81b2e-837e-48ae-90c6-e1df33c1a761)

Closing for now, but please reopen if it's not working for you. cc/ @sylvainsf
