### ISSUE TITLE
Radius docs imply that Azure is not supported

### ISSUE THREAD

**Issue by plwhite** [radius-project/docs#922]
## What content needs to be created or modified?

The Resource schemas section of the docs (<https://docs.radapp.io/reference/resource-schema/>) lists a bunch of local resources (Kubernetes types), and how to manage AWS resources, but doesn't mention Azure. It seemed clear to me that Azure was not supported.

I know this is a Microsoft project so realised that Azure must be supported, and did a search, which showed that of course Azure is a first class citizen (<https://docs.radapp.io/guides/author-apps/azure/overview/>) but this wasn't as clear as it could be.

## Describe the solution you'd like

Just as there is a section for AWS resources in <https://docs.radapp.io/reference/resource-schema/>, there should be one for Azure resources. It could be just a single page with "all Azure resource types are supported; here's how".

## Where should the new material be placed?

See above.

## The associated pull request from the Radius code repo, if applicable

N/A

## Additional context

N/A

[AB#9996](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9996)

**Comment by rynowak** [comment]
Thanks @plwhite - this is great feedback, I can see how that is confusing.

**Comment by jasonviviano** [comment]
@plwhite Thanks again for having called this out! We've added a menu item that can link users to all the supported Azure resources as well as their templating formats in Bicep. I hope that can clarify any confusion for future users. Let me know if you still think this might not be the best solution and we can discuss! If not closing this issue now!
