### ISSUE TITLE
Enhancing Documentation for Supported Terraform Recipe Sources

### ISSUE THREAD

**Issue by kachawla** [radius-project/docs#927]
## What content needs to be created or modified?
Reviewing Recipes overview docs, it looks like we haven't made it explicitly easy for a new user to identify the supported sources for recipes (example: Terraform registry for Terraform and OCI compliant registries for Bicep). This information is currently mentioned under https://docs.radapp.io/guides/recipes/howto-author-recipes/, but it doesn't explicitly indicate that other sources aren't supported.

### Where should the new material be placed?
To enhance clarity, I suggest extending this table at [Support for multiple IaC languages](https://docs.radapp.io/guides/recipes/overview/#support-for-multiple-iac-languages) section, to include supported recipe sources.

Doing this will allow users to quickly identify the sources that are supported, improving the overall user experience when onboarding to recipes.

[AB#10027](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10027)

**Comment by jasonviviano** [comment]
Closing, change merged.
