### ISSUE TITLE
overhaul the FAQ doc

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#93]
https://github.com/project-radius/docs/blob/v0.11/docs/content/concepts/faq.md

This page is out of date - both in terms of incorrect info by now and questions that aren't really important to users anymore. 

We should overhaul this page, maybe by taking a fresh start at what we think the FAQ would be. 

I think we actually need two types of FAQ: a product one and a down-in-the-details one. 
- 1st FAQ page = lightweight page about how Radius fits into the world. For example, 
  - how does Radius relate to Crossplane? to Azure Arc? 
  - does Radius compete with Terraform? 
  - is Radius a deployment engine? 
- 2nd FAQ page ("Best practices?" other name?) = place for technical questions we get a lot about functionality or what our best practices are. For example, 
  - should I use 1 bicep file more > 1 file? 
  - known limitations (like multi-region)? 

[AB#7087](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7087)

**Comment by nicolejms** [comment]
Triage: moving to global backlog

**Comment by AaronCrawfis** [comment]
Updated
