### ISSUE TITLE
Contributing page needs some love

### ISSUE THREAD

**Issue by rynowak** [radius-project/docs#970]
## What content needs to be created or modified?

Per discussion with a contributor, the existing [contributing docs page](https://docs.radapp.io/community/contributing/overview/) wasn't very clear.

I was talking with a contributor, he ultimately needed to find [this page](https://github.com/radius-project/radius/tree/main/docs/contributing/contributing-code/contributing-code-building#generating-code), however he started with `docs.radapp.io`.

Along the way, he saw the existing [contributing docs page](https://docs.radapp.io/community/contributing/overview/) and didn't think it was the right reference, so he kept looking.

## Describe the solution you'd like

It's hard to optimize the docs for every user, but when I look at the page it's clear that we could make some improvements.

These are ideas and we don't have to all of them.

- Do we want to move `Contributing` to lop level in the TOC?
- Do we want to add more tags/keywords in case users aren't thinking about the term `contributing` eg: `repo`, `code`, `pull-request`, `issue`.
- I think we could expand the intro to this page. It's not very clear what I'm going to find at these links.
- We should reorder this table to put `project-radius/radius` and `project-radius/docs` at the top.
- We should rephrase `Radius control plane` to something more general. If you don't know what `control plane` means you're not likely to click it. ~50% of contributors will end up in the Radius repo, and the other ~50% in docs. 
- The `project-radius/radius` link should go to: https://github.com/radius-project/radius/blob/main/CONTRIBUTING.md
- We should remove templates

## Where should the new material be placed?

https://docs.radapp.io/community/contributing/overview/

## Additional context

[AB#10422](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10422)

**Comment by nicolejms** [comment]
specifically on the doc side...
