### ISSUE TITLE
Revisit Radius tutorials/quickstarts

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/docs#98]
## Current state

Today there are two types of examples: tutorials and samples

- Tutorials are step-by-step guides on how to write and deploy an application. They teach the Radius app model and tooling.
   - Webapp introduces applications, containers, HTTP routes, the `rad` CLI, connectors, and starters
   - Dapr introduces traits, Dapr Connectors, and Dapr Routes
- Samples are reference architectures and steps that let readers learn how the Radius app model can be used for various use cases
   - eShop shows a large-scale application that uses containers, HTTP routes, connectors, starters, `rad.yaml`, and direct Azure connections
   - Container Apps Store shows a reference app with Dapr, containers, HTTP routes, and `rad.yaml`, as well as local environments

## Proposal

We should be revisit our samples and tutorials and make sure they are meeting the intended goals, and if there are any value props missing or introduced too early.

As an exercise we should diagram out what concepts we want to introduce, how many we want to group into a tutorial, and then write content and apps that teach the concepts.

Additionally, we should think through branding. Perhaps "tutorials" and "samples" aren't enough or aren't clear.

### Ideas

- "Getting Started": Install CLI/tooling - should we also have someone install an app in 5 minutes? @jasonviviano to investigate
- Create one 30 minute "tutorial" that teaches Radius concepts overall. Completing this one tutorial teaches you what you need to know to go off and "radify" your existing application or write a new one
- Convert our existing tutorials into "quickstarts", which are 15 minute guides that teach a small set of concepts or tasks. We can look to Dapr for examples
- Convert our existing samples into "reference apps", where we have no step-by-step guides, but instead just a repo to clone and deploy
- Have multiple "ways" to deploy apps - codespaces, local, prebuilt containers. Have a source code repo to change things and build your own containers

## Next steps

- [x] #109
- [x] #99
- [x] #100
   - [x] Move webapp quickstart source code into tutorial source code
- [x] #101
- [x] #105
- [x] #106
- [x] #107
- [x] remove placeholder page we had for a gateways quickstart. 
  - decided not to call it out specifically since it's covered in The Tutorial.

[AB#8136](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/8136)

**Comment by emily-potyraj** [comment]
some inspiration from Ryan: https://learn.hashicorp.com/tutorials/terraform/provider-use?in=terraform/providers

**Comment by emily-potyraj** [comment]
@Reshrahim @jasonviviano @AaronCrawfis @ihood - marking this epic and its child tasks as P0 to indicate which of the v0.12 docs tickets we're prioritizing.

**Comment by emily-potyraj** [comment]
assigning to just me since all we have left to do is check that we don't need to move anything else around (eg. pulling samples out to the samples repo), and I'm planning to do a final tree structure pass on the docs picking up a few other structure changes we have issues for.
